# encoding: utf-8
# module Babel.ParserGenerator calls itself ParserGenerator
# from Microsoft.SqlServer.Management.SqlParser, Version=14.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91
# by generator 1.145
""" no doc """
from __future__ import annotations
from System import Enum

"""The following names are not found in the module: field#
"""

# no functions
# classes

class EParseState(Enum): # skipped bases: <type 'IFormattable'>, <type 'IConvertible'>, <type 'IComparable'>, <type 'object'>
    """ enum EParseState, values: e_ParseAfterWith (10), e_ParseBegin (3), e_ParseClose (8), e_ParseDump (5), e_ParseEventNotifObjectOn (1), e_ParseGDR (4), e_ParseGroupBy (11), e_ParseIdxInclude (2), e_ParseLoad (6), e_ParseNeutral (0), e_ParseOpen (7), e_ParseWith (9) """
    e_ParseAfterWith: EParseState = ...
    e_ParseBegin: EParseState = ...
    e_ParseClose: EParseState = ...
    e_ParseDump: EParseState = ...
    e_ParseEventNotifObjectOn: EParseState = ...
    e_ParseGDR: EParseState = ...
    e_ParseGroupBy: EParseState = ...
    e_ParseIdxInclude: EParseState = ...
    e_ParseLoad: EParseState = ...
    e_ParseNeutral: EParseState = ...
    e_ParseOpen: EParseState = ...
    e_ParseWith: EParseState = ...
    value__ = ...


class QueryState(Enum): # skipped bases: <type 'IFormattable'>, <type 'IConvertible'>, <type 'IComparable'>, <type 'object'>
    """ enum QueryState, values: IN_FROM_CLAUSE (6), IN_HAVING_CLAUSE (3), IN_ON_CLAUSE (5), IN_OPTION_CLAUSE (7), IN_ORDER_BY_CLAUSE (2), IN_SELECT_LIST (1), IN_WHERE_CLAUSE (4), None (0) """
    IN_FROM_CLAUSE: QueryState = ...
    IN_HAVING_CLAUSE: QueryState = ...
    IN_ON_CLAUSE: QueryState = ...
    IN_OPTION_CLAUSE: QueryState = ...
    IN_ORDER_BY_CLAUSE: QueryState = ...
    IN_SELECT_LIST: QueryState = ...
    IN_WHERE_CLAUSE: QueryState = ...
    value__ = ...


class QueryStatus(Enum): # skipped bases: <type 'IFormattable'>, <type 'IConvertible'>, <type 'IComparable'>, <type 'object'>
    """ enum QueryStatus, values: None (0), P_BREAKDECPOINT (64), Q_ALTDB (32), Q_BYALL (1), Q_BYCUBE (8), Q_BYROLLUP (16), Q_CR_AL_FTI (512), Q_CRDB (256), Q_DATABASE (8192), Q_DERIVED (2), Q_FN_PARSE (16384), Q_FT_PROP_REF (1024), Q_MERGE (2048), Q_ODBC_ESCAPE (128), Q_SERVER (4096), Q_VIEW (4) """
    P_BREAKDECPOINT: QueryStatus = ...
    Q_ALTDB: QueryStatus = ...
    Q_BYALL: QueryStatus = ...
    Q_BYCUBE: QueryStatus = ...
    Q_BYROLLUP: QueryStatus = ...
    Q_CRDB: QueryStatus = ...
    Q_CR_AL_FTI: QueryStatus = ...
    Q_DATABASE: QueryStatus = ...
    Q_DERIVED: QueryStatus = ...
    Q_FN_PARSE: QueryStatus = ...
    Q_FT_PROP_REF: QueryStatus = ...
    Q_MERGE: QueryStatus = ...
    Q_ODBC_ESCAPE: QueryStatus = ...
    Q_SERVER: QueryStatus = ...
    Q_VIEW: QueryStatus = ...
    value__ = ...


class StatementFlags(Enum): # skipped bases: <type 'IFormattable'>, <type 'IConvertible'>, <type 'IComparable'>, <type 'object'>
    """ enum (flags) StatementFlags, values: P_ALL (8192), P_ALLOW_SELECT (262144), P_ALTER_TAB_SWITCH (134217728), P_ANY (4096), P_ASSIGN (2), P_BATCHPARAM_3PART_NAME (268435456), P_CANTAPPENDTRIG (2097152), P_COLREF (32), P_CONSTONLY (4), P_CREATE_PROC (4194304), P_CURSORDECL (2048), P_CURSORVARS_OK (16384), P_DATEPART (32768), P_DELETE (65536), P_EXISTS (32768), P_HasSubDml (512), P_HOLDLOCK (16), P_IDTFUNC (1024), P_INSERT (16), P_INSERT_EXEC (67108864), P_INSERT_TARGET (8388608), P_LOGFILE (8192), P_NAMEDPARAM (8), P_NO_UDF (524288), P_NOT (16384), P_OLD_HOLDLOCK (32), P_OLD_JOINS (33554432), P_OUTPUT_INTO (1073741824), P_PARSE_TIME_STMT (131072), P_PASSWORD_EXISTS (536870912), P_SCALAREXPR (16777216), P_SCHEMACREATE (4096), P_SELECT (1), P_SELECT_ASSIGN (3), P_SELECTINTO (128), P_TABLEVARS_OK (2147483648), P_UDF_IN_DB (1048576), P_UPDATE (256), P_VIEWCREATE (64) """
    P_ALL: StatementFlags = ...
    P_ALLOW_SELECT: StatementFlags = ...
    P_ALTER_TAB_SWITCH: StatementFlags = ...
    P_ANY: StatementFlags = ...
    P_ASSIGN: StatementFlags = ...
    P_BATCHPARAM_3PART_NAME: StatementFlags = ...
    P_CANTAPPENDTRIG: StatementFlags = ...
    P_COLREF: StatementFlags = ...
    P_CONSTONLY: StatementFlags = ...
    P_CREATE_PROC: StatementFlags = ...
    P_CURSORDECL: StatementFlags = ...
    P_CURSORVARS_OK: StatementFlags = ...
    P_DATEPART: StatementFlags = ...
    P_DELETE: StatementFlags = ...
    P_EXISTS: StatementFlags = ...
    P_HasSubDml: StatementFlags = ...
    P_HOLDLOCK: StatementFlags = ...
    P_IDTFUNC: StatementFlags = ...
    P_INSERT: StatementFlags = ...
    P_INSERT_EXEC: StatementFlags = ...
    P_INSERT_TARGET: StatementFlags = ...
    P_LOGFILE: StatementFlags = ...
    P_NAMEDPARAM: StatementFlags = ...
    P_NOT: StatementFlags = ...
    P_NO_UDF: StatementFlags = ...
    P_OLD_HOLDLOCK: StatementFlags = ...
    P_OLD_JOINS: StatementFlags = ...
    P_OUTPUT_INTO: StatementFlags = ...
    P_PARSE_TIME_STMT: StatementFlags = ...
    P_PASSWORD_EXISTS: StatementFlags = ...
    P_SCALAREXPR: StatementFlags = ...
    P_SCHEMACREATE: StatementFlags = ...
    P_SELECT: StatementFlags = ...
    P_SELECTINTO: StatementFlags = ...
    P_SELECT_ASSIGN: StatementFlags = ...
    P_TABLEVARS_OK: StatementFlags = ...
    P_UDF_IN_DB: StatementFlags = ...
    P_UPDATE: StatementFlags = ...
    P_VIEWCREATE: StatementFlags = ...
    value__ = ...


class TokenTransformContext(Enum): # skipped bases: <type 'IFormattable'>, <type 'IConvertible'>, <type 'IComparable'>, <type 'object'>
    """ enum TokenTransformContext, values: AFFINITY_TYPE (24), AFTER_BEGIN (38), AFTER_END (7), AFTER_FTS_WITH (30), AFTER_WITH (8), AFTER_WITH_EXEC_OPTION (9), AG_REPLICA_OPTION (33), ALTER_DB_OPT (12), ALTER_EXTERNALDATASOURCE_WITH (48), ALTER_SERVER_CONFIG_SET (34), ALTER_SERVER_CONFIG_SET_DIAG_LOG (35), ALTER_SERVER_CONFIG_SET_HADR_CLUSTER (36), ALTER_SERVER_TYPE (27), ALTER_USER_WITH (32), ALTTAB_ACTIONS (21), ALTTAB_ENABLE_DISABLE (23), COL_ADD_DROP_OPT (57), COL_DEF_OPT (58), COL_ENCRYPTION_OR_MASTER_KEY (55), CREATE_DB_OPT (10), CREATE_DB_TYPE (11), CREATE_DROP_ALTER (6), CREATE_EXTERNALDATASOURCE_WITH (47), CREATE_EXTERNALFILEFORMAT_WITH (46), CREATE_EXTERNALTABLE_WITH (49), CREATE_TAB_OPT (40), CREATE_TAB_WITH_OPT (41), CREATE_USER_WITH (31), DB_SCOPED_CONFIG_OPT (59), DUMP_ENCRYPTION_OPT (14), DUMP_OPT (13), EXTERNAL_POOL_AFFINITY_TYPE (26), EXTERNAL_TYPE (50), FILESTREAM_DB_OPT (39), FTS_PROPERTY (29), FULLTEXT_SEARCH (28), GEODR_OPT (56), GRAPH_ID_OR_FILETABLE (60), IN_INLINE_INDEX_SYNTAX (45), IND_ACTIONS (20), IND_OPTIONS (19), INDEX_SORT_OPT (17), LEFT_PAREN_COMPAT (5), LOAD_OPT (15), NONE (0), OPT_STORAGE_ID (18), OPT_SXI_PATH_KIND (43), OPT_SXI_PATH_OPTION (44), OVER_CLAUSE (37), PERSISTENT_LOG_BUFFER_OPT (61), POOL_AFFINITY_TYPE (25), QUERY_STORE_OPT (52), REMOTE_DATA_ARCHIVE_OPT (53), SECURITY_POLICY (51), SEQUENCE_OPTIONS (22), SYSTEM_VERSIONING_OPT (42), TAB_LOCK_OPT (54), TAB_OPT_NAME (16), TOKEN_BEGIN_CS (1), TOKEN_BEGIN_CS_LOOKUP (2), TOKEN_END_CS (3), TOKEN_END_CS_LOOKUP (4) """
    AFFINITY_TYPE: TokenTransformContext = ...
    AFTER_BEGIN: TokenTransformContext = ...
    AFTER_END: TokenTransformContext = ...
    AFTER_FTS_WITH: TokenTransformContext = ...
    AFTER_WITH: TokenTransformContext = ...
    AFTER_WITH_EXEC_OPTION: TokenTransformContext = ...
    AG_REPLICA_OPTION: TokenTransformContext = ...
    ALTER_DB_OPT: TokenTransformContext = ...
    ALTER_EXTERNALDATASOURCE_WITH: TokenTransformContext = ...
    ALTER_SERVER_CONFIG_SET: TokenTransformContext = ...
    ALTER_SERVER_CONFIG_SET_DIAG_LOG: TokenTransformContext = ...
    ALTER_SERVER_CONFIG_SET_HADR_CLUSTER: TokenTransformContext = ...
    ALTER_SERVER_TYPE: TokenTransformContext = ...
    ALTER_USER_WITH: TokenTransformContext = ...
    ALTTAB_ACTIONS: TokenTransformContext = ...
    ALTTAB_ENABLE_DISABLE: TokenTransformContext = ...
    COL_ADD_DROP_OPT: TokenTransformContext = ...
    COL_DEF_OPT: TokenTransformContext = ...
    COL_ENCRYPTION_OR_MASTER_KEY: TokenTransformContext = ...
    CREATE_DB_OPT: TokenTransformContext = ...
    CREATE_DB_TYPE: TokenTransformContext = ...
    CREATE_DROP_ALTER: TokenTransformContext = ...
    CREATE_EXTERNALDATASOURCE_WITH: TokenTransformContext = ...
    CREATE_EXTERNALFILEFORMAT_WITH: TokenTransformContext = ...
    CREATE_EXTERNALTABLE_WITH: TokenTransformContext = ...
    CREATE_TAB_OPT: TokenTransformContext = ...
    CREATE_TAB_WITH_OPT: TokenTransformContext = ...
    CREATE_USER_WITH: TokenTransformContext = ...
    DB_SCOPED_CONFIG_OPT: TokenTransformContext = ...
    DUMP_ENCRYPTION_OPT: TokenTransformContext = ...
    DUMP_OPT: TokenTransformContext = ...
    EXTERNAL_POOL_AFFINITY_TYPE: TokenTransformContext = ...
    EXTERNAL_TYPE: TokenTransformContext = ...
    FILESTREAM_DB_OPT: TokenTransformContext = ...
    FTS_PROPERTY: TokenTransformContext = ...
    FULLTEXT_SEARCH: TokenTransformContext = ...
    GEODR_OPT: TokenTransformContext = ...
    GRAPH_ID_OR_FILETABLE: TokenTransformContext = ...
    INDEX_SORT_OPT: TokenTransformContext = ...
    IND_ACTIONS: TokenTransformContext = ...
    IND_OPTIONS: TokenTransformContext = ...
    IN_INLINE_INDEX_SYNTAX: TokenTransformContext = ...
    LEFT_PAREN_COMPAT: TokenTransformContext = ...
    LOAD_OPT: TokenTransformContext = ...
    NONE: TokenTransformContext = ...
    OPT_STORAGE_ID: TokenTransformContext = ...
    OPT_SXI_PATH_KIND: TokenTransformContext = ...
    OPT_SXI_PATH_OPTION: TokenTransformContext = ...
    OVER_CLAUSE: TokenTransformContext = ...
    PERSISTENT_LOG_BUFFER_OPT: TokenTransformContext = ...
    POOL_AFFINITY_TYPE: TokenTransformContext = ...
    QUERY_STORE_OPT: TokenTransformContext = ...
    REMOTE_DATA_ARCHIVE_OPT: TokenTransformContext = ...
    SECURITY_POLICY: TokenTransformContext = ...
    SEQUENCE_OPTIONS: TokenTransformContext = ...
    SYSTEM_VERSIONING_OPT: TokenTransformContext = ...
    TAB_LOCK_OPT: TokenTransformContext = ...
    TAB_OPT_NAME: TokenTransformContext = ...
    TOKEN_BEGIN_CS: TokenTransformContext = ...
    TOKEN_BEGIN_CS_LOOKUP: TokenTransformContext = ...
    TOKEN_END_CS: TokenTransformContext = ...
    TOKEN_END_CS_LOOKUP: TokenTransformContext = ...
    value__ = ...


