# encoding: utf-8
# module System.Security.Authentication calls itself Authentication
# from System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
# by generator 1.145
""" no doc """
from __future__ import annotations
from System import Enum, SystemException

"""The following names are not found in the module: BoundEvent, field#
"""

# no functions
# classes

class AuthenticationException(SystemException): # skipped bases: <type '_Exception'>, <type 'ISerializable'>, <type 'object'>
    """
    AuthenticationException()
    AuthenticationException(message: str)
    AuthenticationException(message: str, innerException: Exception)
    """
    SerializeObjectState = ...


class CipherAlgorithmType(Enum): # skipped bases: <type 'IFormattable'>, <type 'IConvertible'>, <type 'IComparable'>, <type 'object'>
    """ enum CipherAlgorithmType, values: Aes (26129), Aes128 (26126), Aes192 (26127), Aes256 (26128), Des (26113), None (0), Null (24576), Rc2 (26114), Rc4 (26625), TripleDes (26115) """
    Aes: CipherAlgorithmType = ...
    Aes128: CipherAlgorithmType = ...
    Aes192: CipherAlgorithmType = ...
    Aes256: CipherAlgorithmType = ...
    Des: CipherAlgorithmType = ...
    Null: CipherAlgorithmType = ...
    Rc2: CipherAlgorithmType = ...
    Rc4: CipherAlgorithmType = ...
    TripleDes: CipherAlgorithmType = ...
    value__ = ...


class ExchangeAlgorithmType(Enum): # skipped bases: <type 'IFormattable'>, <type 'IConvertible'>, <type 'IComparable'>, <type 'object'>
    """ enum ExchangeAlgorithmType, values: DiffieHellman (43522), None (0), RsaKeyX (41984), RsaSign (9216) """
    DiffieHellman: ExchangeAlgorithmType = ...
    RsaKeyX: ExchangeAlgorithmType = ...
    RsaSign: ExchangeAlgorithmType = ...
    value__ = ...


class HashAlgorithmType(Enum): # skipped bases: <type 'IFormattable'>, <type 'IConvertible'>, <type 'IComparable'>, <type 'object'>
    """ enum HashAlgorithmType, values: Md5 (32771), None (0), Sha1 (32772), Sha256 (32780), Sha384 (32781), Sha512 (32782) """
    Md5: HashAlgorithmType = ...
    Sha1: HashAlgorithmType = ...
    Sha256: HashAlgorithmType = ...
    Sha384: HashAlgorithmType = ...
    Sha512: HashAlgorithmType = ...
    value__ = ...


class InvalidCredentialException(AuthenticationException): # skipped bases: <type '_Exception'>, <type 'ISerializable'>, <type 'object'>
    """
    InvalidCredentialException()
    InvalidCredentialException(message: str)
    InvalidCredentialException(message: str, innerException: Exception)
    """
    SerializeObjectState = ...


class SslProtocols(Enum): # skipped bases: <type 'IFormattable'>, <type 'IConvertible'>, <type 'IComparable'>, <type 'object'>
    """ enum (flags) SslProtocols, values: Default (240), None (0), Ssl2 (12), Ssl3 (48), Tls (192), Tls11 (768), Tls12 (3072), Tls13 (12288) """
    Default: SslProtocols = ...
    Ssl2: SslProtocols = ...
    Ssl3: SslProtocols = ...
    Tls: SslProtocols = ...
    Tls11: SslProtocols = ...
    Tls12: SslProtocols = ...
    Tls13: SslProtocols = ...
    value__ = ...


# variables with complex values

