# encoding: utf-8
# module System.Windows.Forms.Automation calls itself Automation
# from System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
# by generator 1.145
""" no doc """
from __future__ import annotations
from System import Enum

"""The following names are not found in the module: field#
"""

# no functions
# classes

class AutomationLiveSetting(Enum): # skipped bases: <type 'IFormattable'>, <type 'IConvertible'>, <type 'IComparable'>, <type 'object'>
    """ enum AutomationLiveSetting, values: Assertive (2), Off (0), Polite (1) """
    Assertive: AutomationLiveSetting = ...
    Off: AutomationLiveSetting = ...
    Polite: AutomationLiveSetting = ...
    value__ = ...


class AutomationNotificationKind(Enum): # skipped bases: <type 'IFormattable'>, <type 'IConvertible'>, <type 'IComparable'>, <type 'object'>
    """ enum AutomationNotificationKind, values: ActionAborted (3), ActionCompleted (2), ItemAdded (0), ItemRemoved (1), Other (4) """
    ActionAborted: AutomationNotificationKind = ...
    ActionCompleted: AutomationNotificationKind = ...
    ItemAdded: AutomationNotificationKind = ...
    ItemRemoved: AutomationNotificationKind = ...
    Other: AutomationNotificationKind = ...
    value__ = ...


class AutomationNotificationProcessing(Enum): # skipped bases: <type 'IFormattable'>, <type 'IConvertible'>, <type 'IComparable'>, <type 'object'>
    """ enum AutomationNotificationProcessing, values: All (2), CurrentThenMostRecent (4), ImportantAll (0), ImportantMostRecent (1), MostRecent (3) """
    All: AutomationNotificationProcessing = ...
    CurrentThenMostRecent: AutomationNotificationProcessing = ...
    ImportantAll: AutomationNotificationProcessing = ...
    ImportantMostRecent: AutomationNotificationProcessing = ...
    MostRecent: AutomationNotificationProcessing = ...
    value__ = ...


class IAutomationLiveRegion: # skipped bases: <type 'object'>
    """ no doc """
    @property
    def LiveSetting(self) -> AutomationLiveSetting:
        """
        Get: LiveSetting(self: IAutomationLiveRegion) -> AutomationLiveSetting
        Set: LiveSetting(self: IAutomationLiveRegion) = value
        """
        ...



