# encoding: utf-8
# module Microsoft.SqlServer.Management.SqlParser.Parser calls itself Parser
# from Microsoft.SqlServer.Management.SqlParser, Version=14.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91
# by generator 1.145
""" no doc """
from __future__ import annotations
from Microsoft.SqlServer.Management.SqlParser.Common import (
    DatabaseCompatibilityLevel, TransactSqlVersion)

from Microsoft.SqlServer.Management.SqlParser.SqlCodeDom import SqlScript

from System import Enum, IComparable

from System.Collections import IDictionary, IEnumerable

from System.Xml import XmlWriter

from typing import Tuple as Tuple_

"""The following names are not found in the module: field#
"""

# no functions
# classes

class Error(IComparable): # skipped bases: <type 'object'>
    """ no doc """
    @property
    def End(self) -> Location:
        """ Get: End(self: Error) -> Location """
        ...

    @property
    def IsWarning(self) -> bool:
        """ Get: IsWarning(self: Error) -> bool """
        ...

    @property
    def Message(self) -> str:
        """ Get: Message(self: Error) -> str """
        ...

    @property
    def Start(self) -> Location:
        """ Get: Start(self: Error) -> Location """
        ...

    @property
    def Type(self) -> ErrorType:
        """ Get: Type(self: Error) -> ErrorType """
        ...


    def Equals(self, *__args:Error) -> bool:
        """ Equals(self: Error, error: Error) -> bool """
        ...

    def __eq__(self, *args): #cannot find CLR method
        """ x.__eq__(y) <==> x==y """
        ...


class ErrorFlags(Enum): # skipped bases: <type 'IFormattable'>, <type 'IConvertible'>, <type 'IComparable'>, <type 'object'>
    """ enum (flags) ErrorFlags, values: None (0), UnresolvedDatabaseObjectReference (3), UnresolvedReference (1), UnsupportedTSql (4) """
    UnresolvedDatabaseObjectReference: ErrorFlags = ...
    UnresolvedReference: ErrorFlags = ...
    UnsupportedTSql: ErrorFlags = ...
    value__ = ...


class ErrorType(Enum): # skipped bases: <type 'IFormattable'>, <type 'IConvertible'>, <type 'IComparable'>, <type 'object'>
    """ enum ErrorType, values: BindError (2), ParseError (1), SyntaxError (0) """
    BindError: ErrorType = ...
    ParseError: ErrorType = ...
    SyntaxError: ErrorType = ...
    value__ = ...


class EscapeSequence: # skipped bases: <type 'object'>, <type 'object'>
    """ no doc """
    def Escape(self, value:str) -> str:
        """ Escape(self: EscapeSequence, value: str) -> str """
        ...

    @staticmethod
    def IdentifyEscapeSequence(value:str) -> EscapeSequence:
        """ IdentifyEscapeSequence(value: str) -> EscapeSequence """
        ...

    @staticmethod
    def RequiresEscaping(value:str) -> bool:
        """ RequiresEscaping(value: str) -> bool """
        ...

    def Unescape(self, value:str) -> str:
        """ Unescape(self: EscapeSequence, value: str) -> str """
        ...

    @staticmethod
    def UnescapeIdentifier(value:str) -> str:
        """ UnescapeIdentifier(value: str) -> str """
        ...

    @staticmethod
    def UnescapeLiteral(value, isUnicode) -> Tuple_[str, bool]:
        """ UnescapeLiteral(value: str) -> (str, bool) """
        ...

    BracketedEscapeSequence: EscapeSequence = ...
    DoubleQuotedEscapeSequence: EscapeSequence = ...
    SingleQuotedEscapeSequence: EscapeSequence = ...


class Location(IComparable): # skipped bases: <type 'object'>
    """ Location(lineNumber: int, columnNumber: int, offset: int) """
    def ToString(self) -> str:
        """ ToString(self: Location) -> str """
        ...

    ColumnNumber = ...
    LineNumber = ...
    Offset = ...


class PairMatch: # skipped bases: <type 'object'>, <type 'object'>
    """ no doc """
    def ToString(self) -> str:
        """ ToString(self: PairMatch) -> str """
        ...

    EndToken = ...
    IsStartEnd = ...
    StartToken = ...


class ParseOptions: # skipped bases: <type 'object'>, <type 'object'>
    """
    ParseOptions()
    ParseOptions(batchSeparator: str)
    ParseOptions(isQuotedIdentifierSet: bool)
    ParseOptions(batchSeparator: str, isQuotedIdentifierSet: bool)
    ParseOptions(batchSeparator: str, isQuotedIdentifierSet: bool, compatibilityLevel: DatabaseCompatibilityLevel)
    ParseOptions(batchSeparator: str, isQuotedIdentifierSet: bool, compatibilityLevel: DatabaseCompatibilityLevel, transactSqlVersion: TransactSqlVersion)
    """
    @property
    def BatchSeparator(self) -> str:
        """
        Get: BatchSeparator(self: ParseOptions) -> str
        Set: BatchSeparator(self: ParseOptions) = value
        """
        ...

    @property
    def CompatibilityLevel(self) -> DatabaseCompatibilityLevel:
        """
        Get: CompatibilityLevel(self: ParseOptions) -> DatabaseCompatibilityLevel
        Set: CompatibilityLevel(self: ParseOptions) = value
        """
        ...

    @property
    def IsErrorRecoveryEnabled(self) -> bool:
        """
        Get: IsErrorRecoveryEnabled(self: ParseOptions) -> bool
        Set: IsErrorRecoveryEnabled(self: ParseOptions) = value
        """
        ...

    @property
    def IsQuotedIdentifierSet(self) -> bool:
        """
        Get: IsQuotedIdentifierSet(self: ParseOptions) -> bool
        Set: IsQuotedIdentifierSet(self: ParseOptions) = value
        """
        ...

    @property
    def TransactSqlVersion(self) -> TransactSqlVersion:
        """
        Get: TransactSqlVersion(self: ParseOptions) -> TransactSqlVersion
        Set: TransactSqlVersion(self: ParseOptions) = value
        """
        ...


    def Equals(self, *__args:ParseOptions) -> bool:
        """ Equals(self: ParseOptions, other: ParseOptions) -> bool """
        ...

    def __eq__(self, *args): #cannot find CLR method
        """ x.__eq__(y) <==> x==y """
        ...


class Parser: # skipped bases: <type 'object'>, <type 'object'>
    """ no doc """
    @staticmethod
    def IncrementalParse(sql, prevResult, options=None, resultOptions=None) -> ParseResult:
        """
        IncrementalParse(sql: str, prevResult: ParseResult) -> ParseResult
        IncrementalParse(sql: str, prevResult: ParseResult, options: ParseOptions) -> ParseResult
        IncrementalParse(sql: str, prevResult: ParseResult, options: ParseOptions) -> (ParseResult, ParseOptions)
        """
        ...

    @staticmethod
    def Parse(sql, options=None, resultOptions=None) -> ParseResult:
        """
        Parse(sql: str) -> ParseResult
        Parse(sql: str, options: ParseOptions) -> ParseResult
        Parse(sql: str, options: ParseOptions) -> (ParseResult, ParseOptions)
        """
        ...

    __all__: list = ...


class ParseResult: # skipped bases: <type 'object'>, <type 'object'>
    """ no doc """
    @property
    def BatchCount(self) -> int:
        """ Get: BatchCount(self: ParseResult) -> int """
        ...

    @property
    def Errors(self) -> IEnumerable:
        """ Get: Errors(self: ParseResult) -> IEnumerable[Error] """
        ...

    @property
    def Script(self) -> SqlScript:
        """ Get: Script(self: ParseResult) -> SqlScript """
        ...


    def GetTokenNumber(self, line:int, col:int) -> int:
        """ GetTokenNumber(self: ParseResult, line: int, col: int) -> int """
        ...


class ParseUtils: # skipped bases: <type 'object'>, <type 'object'>
    """ no doc """
    @staticmethod
    def RetrieveModuleDefinition(sql:str, parseOptions:ParseOptions) -> IDictionary:
        """ RetrieveModuleDefinition(sql: str, parseOptions: ParseOptions) -> IDictionary[str, object] """
        ...

    @staticmethod
    def RetrieveTriggerDefinition(sql:str, parseOptions:ParseOptions) -> IDictionary:
        """ RetrieveTriggerDefinition(sql: str, parseOptions: ParseOptions) -> IDictionary[str, object] """
        ...

    @staticmethod
    def RetrieveViewDefinition(sql:str, parseOptions:ParseOptions) -> IDictionary:
        """ RetrieveViewDefinition(sql: str, parseOptions: ParseOptions) -> IDictionary[str, object] """
        ...

    __all__: list = ...


class PropertyKeys: # skipped bases: <type 'object'>, <type 'object'>
    """ no doc """
    BodyDefinition: str = ...
    DatabaseName: str = ...
    DefaultValue: str = ...
    HasCheckOption: str = ...
    HasColumnSpecification: str = ...
    ModuleType: str = ...
    Name: str = ...
    Parameters: str = ...
    QueryDefinition: str = ...
    SchemaName: str = ...
    TableVariableName: str = ...
    __all__: list = ...


class Scanner: # skipped bases: <type 'object'>, <type 'object'>
    """ Scanner(options: ParseOptions) """
    def GetNext(self, state, start, end, isPairMatch, isExecAutoParamHelp) -> Tuple_[int, int, int, int, bool, bool]:
        """ GetNext(self: Scanner, state: int) -> (int, int, int, int, bool, bool) """
        ...

    def SetSource(self, source:str, offset:int): # -> 
        """ SetSource(self: Scanner, source: str, offset: int) """
        ...


class StatementEventType(Enum): # skipped bases: <type 'IFormattable'>, <type 'IConvertible'>, <type 'IComparable'>, <type 'object'>
    """ enum StatementEventType, values: NotReusable (0), RejectedByPosition (2), RejectedByState (3), Reused (1) """
    NotReusable: StatementEventType = ...
    RejectedByPosition: StatementEventType = ...
    RejectedByState: StatementEventType = ...
    Reused: StatementEventType = ...
    value__ = ...


class Token: # skipped bases: <type 'object'>, <type 'object'>
    """ no doc """
    @property
    def EndLocation(self) -> Location:
        """ Get: EndLocation(self: Token) -> Location """
        ...

    @property
    def Id(self) -> int:
        """ Get: Id(self: Token) -> int """
        ...

    @property
    def IsSignificant(self) -> bool:
        """ Get: IsSignificant(self: Token) -> bool """
        ...

    @property
    def StartLocation(self) -> Location:
        """ Get: StartLocation(self: Token) -> Location """
        ...

    @property
    def Text(self) -> str:
        """ Get: Text(self: Token) -> str """
        ...

    @property
    def Type(self) -> str:
        """ Get: Type(self: Token) -> str """
        ...

    @property
    def Xml(self) -> str:
        """ Get: Xml(self: Token) -> str """
        ...


    def ToString(self) -> str:
        """ ToString(self: Token) -> str """
        ...

    def WriteXml(self, writer:XmlWriter): # -> 
        """ WriteXml(self: Token, writer: XmlWriter) """
        ...


class Tokens(Enum): # skipped bases: <type 'IFormattable'>, <type 'IConvertible'>, <type 'IComparable'>, <type 'object'>
    """ enum Tokens, values: accumulators (848), END_AFFINITY_TYPE_SUBTOKENS (589), END_AFTER_BEGIN_SUBTOKENS (658), END_AFTER_END_SUBTOKENS (450), END_AFTER_FTS_WITH_SUBTOKENS (619), END_AFTER_WITH_EXEC_OPTION_SUBTOKENS (459), END_AFTER_WITH_SUBTOKENS (455), END_AG_REPLICA_OPTION_SUBTOKENS (633), END_ALTER_DB_OPT_SUBTOKENS (494), END_ALTER_EXTERNALDATASOURCE_WITH_SUBTOKENS (756), END_ALTER_SERVER_CONFIG_SET_DIAG_LOG_SUBTOKENS (648), END_ALTER_SERVER_CONFIG_SET_HADR_CLUSTER_SUBTOKENS (651), END_ALTER_SERVER_CONFIG_SET_SUBTOKENS (641), END_ALTER_SERVER_TYPE_SUBTOKENS (602), END_ALTER_USER_WITH_SUBTOKENS (629), END_ALTTAB_ACTIONS_SUBTOKENS (571), END_ALTTAB_ENABLE_DISABLE_SUBTOKENS (585), END_COL_ADD_DROP_OPT_SUBTOKENS (538), END_COL_DEF_OPT_SUBTOKENS (532), END_COL_ENCRYPTION_OR_MASTER_KEY_SUBTOKENS (794), END_CREATE_DB_OPT_SUBTOKENS (465), END_CREATE_DB_TYPE_SUBTOKENS (469), END_CREATE_DROP_ALTER_SUBTOKENS (445), END_CREATE_EXTERNALDATASOURCE_WITH_SUBTOKENS (735), END_CREATE_EXTERNALFILEFORMAT_WITH_SUBTOKENS (722), END_CREATE_EXTERNALTABLE_WITH_SUBTOKENS (751), END_CREATE_TAB_OPT_SUBTOKENS (667), END_CREATE_TAB_WITH_OPT_SUBTOKENS (679), END_CREATE_USER_WITH_SUBTOKENS (624), END_DB_SCOPED_CONFIG_OPT_SUBTOKENS (803), END_DEPRECATED_TOKENS (841), END_DUMP_ENCRYPTION_OPT_SUBTOKENS (504), END_DUMP_OPT_SUBTOKENS (498), END_EXTERNAL_POOL_AFFINITY_TYPE_SUBTOKENS (597), END_EXTERNAL_TYPE_SUBTOKENS (764), END_FILESTREAM_DB_OPT_SUBTOKENS (662), END_FTS_PROPERTY_SUBTOKENS (614), END_FULLTEXT_SEARCH_SUBTOKENS (610), END_GEODR_OPT_SUBTOKENS (799), END_GRAPH_ID_OR_FILETABLE_SUBTOKENS (808), END_IN_INLINE_INDEX_SYNTAX_SUBTOKENS (697), END_IND_ACTIONS_SUBTOKENS (566), END_IND_OPTIONS_SUBTOKENS (558), END_INDEX_SORT_OPT_SUBTOKENS (523), END_LEFT_PAREN_COMPAT_SUBTOKENS (399), END_LOAD_OPT_SUBTOKENS (508), END_MISSING_TOKENS (833), END_OPT_STORAGE_ID_SUBTOKENS (542), END_OPT_SXI_PATH_KIND_SUBTOKENS (688), END_OPT_SXI_PATH_OPTION_SUBTOKENS (692), END_OVER_CLAUSE_SUBTOKENS (655), END_PERSISTENT_LOG_BUFFER_OPT_SUBTOKENS (811), END_POOL_AFFINITY_TYPE_SUBTOKENS (593), END_QUERY_STORE_OPT_SUBTOKENS (776), END_REMOTE_DATA_ARCHIVE_OPT_SUBTOKENS (781), END_SECURITY_POLICY_SUBTOKENS (704), END_SEQUENCE_OPTIONS_SUBTOKENS (581), END_SYSTEM_VERSIONING_OPT_SUBTOKENS (684), END_TAB_LOCK_OPT_SUBTOKENS (519), END_TAB_OPT_NAME_SUBTOKENS (515), EOF (128), error (127), error_1_discard_max (131), error_unlimited_discard (132), Highest (161), LAST_TOKEN (852), LEX_ACCUMULATE_BINARY (851), LEX_ACCUMULATE_ID (849), LEX_ACCUMULATE_STRING (850), LEX_BATCH_SEPERATOR (846), LEX_END_OF_LINE_COMMENT (844), LEX_ERROR (834), LEX_MULTILINE_COMMENT (845), LEX_WHITE (843), lower_than_grant (134), lower_than_left_paren (133), Lowest (130), maxParseToken (842), NON_EMPTY (129), SQL_CMD_MODE_TOKEN (847), START_AFFINITY_TYPE_SUBTOKENS (586), START_AFTER_BEGIN_SUBTOKENS (656), START_AFTER_END_SUBTOKENS (446), START_AFTER_FTS_WITH_SUBTOKENS (615), START_AFTER_WITH_EXEC_OPTION_SUBTOKENS (456), START_AFTER_WITH_SUBTOKENS (451), START_AG_REPLICA_OPTION_SUBTOKENS (630), START_ALTER_DB_OPT_SUBTOKENS (470), START_ALTER_EXTERNALDATASOURCE_WITH_SUBTOKENS (752), START_ALTER_SERVER_CONFIG_SET_DIAG_LOG_SUBTOKENS (642), START_ALTER_SERVER_CONFIG_SET_HADR_CLUSTER_SUBTOKENS (649), START_ALTER_SERVER_CONFIG_SET_SUBTOKENS (634), START_ALTER_SERVER_TYPE_SUBTOKENS (598), START_ALTER_USER_WITH_SUBTOKENS (625), START_ALTTAB_ACTIONS_SUBTOKENS (567), START_ALTTAB_ENABLE_DISABLE_SUBTOKENS (582), START_COL_ADD_DROP_OPT_SUBTOKENS (533), START_COL_DEF_OPT_SUBTOKENS (524), START_COL_ENCRYPTION_OR_MASTER_KEY_SUBTOKENS (782), START_CREATE_DB_OPT_SUBTOKENS (460), START_CREATE_DB_TYPE_SUBTOKENS (466), START_CREATE_DROP_ALTER_SUBTOKENS (400), START_CREATE_EXTERNALDATASOURCE_WITH_SUBTOKENS (723), START_CREATE_EXTERNALFILEFORMAT_WITH_SUBTOKENS (705), START_CREATE_EXTERNALTABLE_WITH_SUBTOKENS (736), START_CREATE_TAB_OPT_SUBTOKENS (663), START_CREATE_TAB_WITH_OPT_SUBTOKENS (668), START_CREATE_USER_WITH_SUBTOKENS (620), START_DB_SCOPED_CONFIG_OPT_SUBTOKENS (800), START_DEPRECATED_TOKENS (837), START_DUMP_ENCRYPTION_OPT_SUBTOKENS (499), START_DUMP_OPT_SUBTOKENS (495), START_EXTERNAL_POOL_AFFINITY_TYPE_SUBTOKENS (594), START_EXTERNAL_TYPE_SUBTOKENS (757), START_FILESTREAM_DB_OPT_SUBTOKENS (659), START_FTS_PROPERTY_SUBTOKENS (611), START_FULLTEXT_SEARCH_SUBTOKENS (603), START_GEODR_OPT_SUBTOKENS (795), START_GRAPH_ID_OR_FILETABLE_SUBTOKENS (804), START_IN_INLINE_INDEX_SYNTAX_SUBTOKENS (693), START_IND_ACTIONS_SUBTOKENS (559), START_IND_OPTIONS_SUBTOKENS (543), START_INDEX_SORT_OPT_SUBTOKENS (520), START_LEFT_PAREN_COMPAT_SUBTOKENS (396), START_LOAD_OPT_SUBTOKENS (505), START_MISSING_TOKENS (815), START_OPT_STORAGE_ID_SUBTOKENS (539), START_OPT_SXI_PATH_KIND_SUBTOKENS (685), START_OPT_SXI_PATH_OPTION_SUBTOKENS (689), START_OVER_CLAUSE_SUBTOKENS (652), START_PERSISTENT_LOG_BUFFER_OPT_SUBTOKENS (809), START_POOL_AFFINITY_TYPE_SUBTOKENS (590), START_QUERY_STORE_OPT_SUBTOKENS (765), START_REMOTE_DATA_ARCHIVE_OPT_SUBTOKENS (777), START_SECURITY_POLICY_SUBTOKENS (698), START_SEQUENCE_OPTIONS_SUBTOKENS (572), START_SYSTEM_VERSIONING_OPT_SUBTOKENS (680), START_TAB_LOCK_OPT_SUBTOKENS (516), START_TAB_OPT_NAME_SUBTOKENS (509), TOKEN_ADD (148), TOKEN_ADD_EQ (190), TOKEN_ALL (198), TOKEN_ALTER (199), TOKEN_AND (136), TOKEN_ANY (202), TOKEN_AS (203), TOKEN_ASC (205), TOKEN_AUDIT_SPECIFICATION (385), TOKEN_AUTHORIZATION (201), TOKEN_BEGIN (206), TOKEN_BEGIN_CATCH (372), TOKEN_BEGIN_CS (835), TOKEN_BEGIN_TRY (373), TOKEN_BETWEEN (207), TOKEN_BINARY (180), TOKEN_BREAK (208), TOKEN_BROWSE (209), TOKEN_BULK (210), TOKEN_BW_AND_EQ (195), TOKEN_BW_OR_EQ (196), TOKEN_BW_XOR_EQ (197), TOKEN_BY (211), TOKEN_c_ASSEMBLY (366), TOKEN_c_ASYMMETRIC (365), TOKEN_c_AT_TIME_ZONE (138), TOKEN_c_CERT (358), TOKEN_c_CONVERSATION (370), TOKEN_c_COUNTERSIGNATURE (377), TOKEN_c_CUBE (378), TOKEN_c_DIALOG (369), TOKEN_c_DISABLE (354), TOKEN_c_ENABLE (353), TOKEN_c_FOR_SYSTEM_TIME (393), TOKEN_c_GET (351), TOKEN_c_INCLUDE (361), TOKEN_c_LOG (376), TOKEN_c_LOGIN (356), TOKEN_c_MASTER (362), TOKEN_c_MATCH (395), TOKEN_c_MOVE (349), TOKEN_c_NAME (367), TOKEN_c_NEXTVALUE (374), TOKEN_c_OPENJSON (394), TOKEN_c_QUEUE (357), TOKEN_c_RECEIVE (350), TOKEN_c_REVERT (382), TOKEN_c_ROLLUP (379), TOKEN_c_SEND (352), TOKEN_c_SERVER (360), TOKEN_c_SERVICE (355), TOKEN_c_SIGNATURE (364), TOKEN_c_SYMMETRIC (363), TOKEN_c_THROW (371), TOKEN_c_TYPE (368), TOKEN_c_USING (384), TOKEN_c_WITHIN_GROUP (375), TOKEN_c_XMLSCHEMA (359), TOKEN_CASCADE (220), TOKEN_CASE (212), TOKEN_CHECK (323), TOKEN_CHECKPOINT (213), TOKEN_CLOSE (316), TOKEN_CLUSTERED (214), TOKEN_COALESCE (215), TOKEN_COLLATE (216), TOKEN_COLUMN (343), TOKEN_COMMIT (217), TOKEN_COMPUTE (218), TOKEN_CONSTRAINT (319), TOKEN_CONTAINS (347), TOKEN_CONTAINSTABLE (345), TOKEN_CONTINUE (219), TOKEN_CONVERT (221), TOKEN_CREATE (145), TOKEN_CROSS (151), TOKEN_CURRENT (315), TOKEN_CURRENT_DATE (332), TOKEN_CURRENT_TIME (333), TOKEN_CURRENT_TIMESTAMP (334), TOKEN_CURRENT_USER (329), TOKEN_CURSOR (312), TOKEN_DATABASE (223), TOKEN_DB_SCOPED_CONFIG (388), TOKEN_DB_SCOPED_CREDENTIAL (387), TOKEN_DBCC (225), TOKEN_DEALLOCATE (317), TOKEN_DECLARE (226), TOKEN_DEFAULT (227), TOKEN_DELETE (228), TOKEN_DENY (146), TOKEN_DESC (229), TOKEN_DISTINCT (230), TOKEN_DISTRIBUTED (335), TOKEN_DIV_EQ (193), TOKEN_DOLLAR_PARTITION (380), TOKEN_DOUBLE (231), TOKEN_DOUBLECOLON (139), TOKEN_DROP (147), TOKEN_DUMP (232), TOKEN_ELSE (140), TOKEN_EMBEDED_DOT_NUMERIC (814), TOKEN_ENCRYPTION_KEY (386), TOKEN_END (233), TOKEN_END_CS (836), TOKEN_ERRLVL (234), TOKEN_ESCAPE (236), TOKEN_EXCEPT (235), TOKEN_EXECUTE (237), TOKEN_EXISTS (238), TOKEN_EXIT (239), TOKEN_EXTERNAL (240), TOKEN_FETCH (150), TOKEN_FILE (241), TOKEN_FILLFACTOR (242), TOKEN_FOR (243), TOKEN_FOREIGN (325), TOKEN_FREETEXT (348), TOKEN_FREETEXTTABLE (346), TOKEN_FROM (244), TOKEN_FULL (152), TOKEN_FUNCTION (245), TOKEN_GLOBAL_VAR (183), TOKEN_GOTO (246), TOKEN_GRAMMAR_COMPUTED_COLS (171), TOKEN_GRAMMAR_FILTERED_INDEX_EXPR (170), TOKEN_GRAMMAR_FILTERED_INDEXES (169), TOKEN_GRAMMAR_OPTION_CLAUSE (167), TOKEN_GRAMMAR_RECOMPILE (166), TOKEN_GRAMMAR_SECURITY_PREDICATE (172), TOKEN_GRAMMAR_SPCURSORDML (165), TOKEN_GRAMMAR_SPCURSOROPEN (163), TOKEN_GRAMMAR_SPCURSOROPEN_PROC (164), TOKEN_GRAMMAR_STANDARD_TSQL (162), TOKEN_GRAMMAR_XEVENT_PREDICATE (168), TOKEN_GRANT (143), TOKEN_GROUP (247), TOKEN_HAVING (248), TOKEN_HOLDLOCK (249), TOKEN_ID (173), TOKEN_IDENTITY (250), TOKEN_IDENTITY_INSERT (290), TOKEN_IDENTITYCOL (251), TOKEN_IF (252), TOKEN_IMAGE (179), TOKEN_IN (253), TOKEN_INDEX (254), TOKEN_INNER (153), TOKEN_INSERT (255), TOKEN_INTEGER (182), TOKEN_INTERSECT (256), TOKEN_INTO (257), TOKEN_IS (258), TOKEN_JOIN (158), TOKEN_KEY (321), TOKEN_KILL (259), TOKEN_LABEL (181), TOKEN_LEADING_DOT_NUMERIC (812), TOKEN_LEFT (155), TOKEN_LEFT_PAREN_80 (397), TOKEN_LEFT_PAREN_90 (398), TOKEN_LIKE (260), TOKEN_LINENO (261), TOKEN_LOAD (262), TOKEN_LOG_ON (272), TOKEN_MERGE (383), TOKEN_MISSING_AND (822), TOKEN_MISSING_BEGIN_CATCH (831), TOKEN_MISSING_CATCH (832), TOKEN_MISSING_COMMA (828), TOKEN_MISSING_END (820), TOKEN_MISSING_EQUAL (821), TOKEN_MISSING_INSERT_SOURCE (827), TOKEN_MISSING_LITERAL (824), TOKEN_MISSING_ON (816), TOKEN_MISSING_RIGHT_PAREN (817), TOKEN_MISSING_SET (825), TOKEN_MISSING_SQLID (826), TOKEN_MISSING_STRING_VAR (823), TOKEN_MISSING_THEN (819), TOKEN_MISSING_TRY (830), TOKEN_MISSING_VARIABLE (829), TOKEN_MISSING_WHEN (818), TOKEN_MOD_EQ (194), TOKEN_MONEY (185), TOKEN_MULT_EQ (192), TOKEN_NATIONAL (264), TOKEN_NOCHECK (326), TOKEN_NONCLUSTERED (265), TOKEN_NOT (137), TOKEN_NOT_FOR (266), TOKEN_NULL (267), TOKEN_NULLIF (268), TOKEN_NUMERIC (186), TOKEN_ODBC_PREFIX (188), TOKEN_ODBC_TERMINATOR (189), TOKEN_OF (313), TOKEN_OFF (269), TOKEN_OFFSETS (270), TOKEN_ON (271), TOKEN_OPEN (314), TOKEN_OPENDATASOURCE (341), TOKEN_OPENQUERY (339), TOKEN_OPENROWSET (340), TOKEN_OPENXML (342), TOKEN_OPTION (273), TOKEN_OR (135), TOKEN_ORDER (274), TOKEN_OUTER (154), TOKEN_OVER (275), TOKEN_PERCENT (337), TOKEN_PIVOT (159), TOKEN_PLAN (276), TOKEN_PRIMARY (320), TOKEN_PRINT (277), TOKEN_PROC_SEMI (338), TOKEN_PROCEDURE (278), TOKEN_PSEUDOCOL (177), TOKEN_PUBLIC (279), TOKEN_QUOTED_ID (174), TOKEN_RAISERROR (280), TOKEN_READ (318), TOKEN_READTEXT (281), TOKEN_REAL (184), TOKEN_RECONFIGURE (282), TOKEN_REFERENCES (322), TOKEN_REPLICATION (327), TOKEN_REQJOIN (187), TOKEN_RESTRICT (224), TOKEN_RETURN (283), TOKEN_REVERT (381), TOKEN_REVOKE (144), TOKEN_RIGHT (156), TOKEN_ROLLBACK (284), TOKEN_ROWCOUNT (285), TOKEN_ROWGUIDCOL (324), TOKEN_RULE (286), TOKEN_s_AB_ATOMIC (657), TOKEN_s_AE_CATCH (447), TOKEN_s_AE_CONVERSATION (448), TOKEN_s_AE_TRY (449), TOKEN_s_AEDS_CREDENTIAL (755), TOKEN_s_AEDS_LOCATION (753), TOKEN_s_AEDS_RESOURCEMANAGERLOCATION (754), TOKEN_s_aff_CPU (587), TOKEN_s_aff_NUMA (588), TOKEN_s_AFW_PROPERTY_DESCRIPTION (618), TOKEN_s_AFW_PROPERTY_INT_ID (617), TOKEN_s_AFW_PROPERTY_SET_GUID (616), TOKEN_s_AG_ROLE_AGNOSTIC_OPTION (631), TOKEN_s_AG_ROLE_SPECIFIC_OPTION (632), TOKEN_s_ALTDBOPT_AUTO_CRT_STATS (489), TOKEN_s_ALTDBOPT_CHANGE_TRACKING (471), TOKEN_s_ALTDBOPT_CONTAINEDDB (476), TOKEN_s_ALTDBOPT_DELAYED_DURABILITY (478), TOKEN_s_ALTDBOPT_DIST_POLICY (474), TOKEN_s_ALTDBOPT_failover (479), TOKEN_s_ALTDBOPT_filegroup (486), TOKEN_s_ALTDBOPT_FILESTREAM (472), TOKEN_s_ALTDBOPT_force_failover (483), TOKEN_s_ALTDBOPT_HADR (475), TOKEN_s_ALTDBOPT_HARDENING (492), TOKEN_s_ALTDBOPT_log (485), TOKEN_s_ALTDBOPT_modify (481), TOKEN_s_ALTDBOPT_name (487), TOKEN_s_ALTDBOPT_OTHER (473), TOKEN_s_ALTDBOPT_PERSISTENT_LOG_BUFFER (493), TOKEN_s_ALTDBOPT_QUERY_STORE (488), TOKEN_s_ALTDBOPT_rebuild (482), TOKEN_s_ALTDBOPT_RECOVERY (477), TOKEN_s_ALTDBOPT_REMOTE_DATA_ARCHIVE (490), TOKEN_s_ALTDBOPT_remove (480), TOKEN_s_ALTDBOPT_SECONDARY (484), TOKEN_s_ALTDBOPT_TEMPORAL_RETENTION (491), TOKEN_s_altserv_AUDIT (599), TOKEN_s_altserv_CONFIG (600), TOKEN_s_altserv_config_set_BUFFER_POOL_EXTENSION (639), TOKEN_s_altserv_config_set_diaglog_MAX_FILES (645), TOKEN_s_altserv_config_set_diaglog_MAX_SIZE (644), TOKEN_s_altserv_config_set_diaglog_OFF (647), TOKEN_s_altserv_config_set_diaglog_ON (646), TOKEN_s_altserv_config_set_diaglog_PATH (643), TOKEN_s_altserv_config_set_DIAGNOSTICS (637), TOKEN_s_altserv_config_set_FAILOVER (636), TOKEN_s_altserv_config_set_HADR (638), TOKEN_s_altserv_config_set_hadr_cluster_CONTEXT (650), TOKEN_s_altserv_config_set_PROCESS (635), TOKEN_s_altserv_config_set_SOFTNUMA (640), TOKEN_s_altserv_ROLE (601), TOKEN_s_ALTTAB_DISABLE_ENABLE (568), TOKEN_s_ALTTAB_EN_CHANGE_TRACKING (583), TOKEN_s_ALTTAB_EN_FILETABLE_NAMESPACE (584), TOKEN_s_ALTTAB_REBUILD (569), TOKEN_s_ALTTAB_SWITCH (570), TOKEN_s_AUW_PASSWORD (626), TOKEN_s_AUW_PROPERTY (627), TOKEN_s_AUW_SID (628), TOKEN_s_AW_CHANGE_TRACKING_CONTEXT (453), TOKEN_s_AW_ID (454), TOKEN_s_AW_XMLNAMESPACES (452), TOKEN_s_AWEO_RECOMPILE (458), TOKEN_s_AWEO_RESULT (457), TOKEN_s_CDA_AGGREGATE (403), TOKEN_s_CDA_APPLICATION (413), TOKEN_s_CDA_ASSEMBLY (402), TOKEN_s_CDA_ASYMMETRIC (425), TOKEN_s_CDA_AUDIT (442), TOKEN_s_CDA_AVAILABILITY (440), TOKEN_s_CDA_BROKER (427), TOKEN_s_CDA_CERT (420), TOKEN_s_CDA_COLUMNSTORE (441), TOKEN_s_CDA_CONTRACT (416), TOKEN_s_CDA_COUNTER (426), TOKEN_s_CDA_CREDENTIAL (424), TOKEN_s_CDA_CRYPTOGRAPHIC (438), TOKEN_s_CDA_ENDPOINT (409), TOKEN_s_CDA_EVENT (404), TOKEN_s_CDA_FULLTEXT (406), TOKEN_s_CDA_GOVERNOR (435), TOKEN_s_CDA_LOGIN (412), TOKEN_s_CDA_MASTER (421), TOKEN_s_CDA_MESSAGE (408), TOKEN_s_CDA_NOTIFICATION (429), TOKEN_s_CDA_PARTITION (405), TOKEN_s_CDA_POLICY (444), TOKEN_s_CDA_POOL (434), TOKEN_s_CDA_QUEUE (415), TOKEN_s_CDA_REMOTE (419), TOKEN_s_CDA_RESOURCE (432), TOKEN_s_CDA_ROLE (414), TOKEN_s_CDA_ROUTE (417), TOKEN_s_CDA_SEARCH (439), TOKEN_s_CDA_SECURITY (443), TOKEN_s_CDA_SELECTIVE (437), TOKEN_s_CDA_SEQUENCE (411), TOKEN_s_CDA_SERVER (431), TOKEN_s_CDA_SERVICE (407), TOKEN_s_CDA_SESSION (428), TOKEN_s_CDA_SIGNATURE (423), TOKEN_s_CDA_SPATIAL (436), TOKEN_s_CDA_SYMMETRIC (422), TOKEN_s_CDA_SYNONYM (410), TOKEN_s_CDA_TARGET (430), TOKEN_s_CDA_TYPE (401), TOKEN_s_CDA_WORKLOAD (433), TOKEN_s_CDA_XML (418), TOKEN_s_CEDS_CREDENTIAL (729), TOKEN_s_CEDS_DATABASENAME (728), TOKEN_s_CEDS_HADOOP (731), TOKEN_s_CEDS_JOBTRACKERLOCATION (726), TOKEN_s_CEDS_LOCATION (725), TOKEN_s_CEDS_RDBMS (732), TOKEN_s_CEDS_RESOURCEMANAGERLOCATION (727), TOKEN_s_CEDS_SHARDMAPMANAGER (733), TOKEN_s_CEDS_SHARDMAPNAME (730), TOKEN_s_CEDS_SHAREDMEMORY (734), TOKEN_s_CEDS_TYPE (724), TOKEN_s_CEFF_DATA_COMPRESSION (708), TOKEN_s_CEFF_DATEFORMAT (711), TOKEN_s_CEFF_DELIMITEDTEXT (718), TOKEN_s_CEFF_ENCODING (714), TOKEN_s_CEFF_FALSE (717), TOKEN_s_CEFF_FIELDTERMINATOR (709), TOKEN_s_CEFF_FORMAT_OPTIONS (706), TOKEN_s_CEFF_FORMAT_TYPE (707), TOKEN_s_CEFF_ORC (720), TOKEN_s_CEFF_PARQUET (721), TOKEN_s_CEFF_RCFILE (719), TOKEN_s_CEFF_ROWTERMINATOR (715), TOKEN_s_CEFF_SERDEMETHOD (713), TOKEN_s_CEFF_STRINGDELIMITER (710), TOKEN_s_CEFF_TRUE (716), TOKEN_s_CEFF_USETYPEDEFAULT (712), TOKEN_s_CEMK_ALGORITHM (789), TOKEN_s_CEMK_COL_ENCRYPTION_KEY (792), TOKEN_s_CEMK_COL_MASTER_KEY (784), TOKEN_s_CEMK_ENCRYPTED_VAL (790), TOKEN_s_CEMK_ENCRYPTION (788), TOKEN_s_CEMK_ENCRYPTION_TYPE (793), TOKEN_s_CEMK_KEYSTORETYPE (785), TOKEN_s_CEMK_MASTER (783), TOKEN_s_CEMK_PATH (787), TOKEN_s_CEMK_PROVIDER_NAME (786), TOKEN_s_CEMK_VALUE (791), TOKEN_s_CET_DATASOURCE (737), TOKEN_s_CET_DISTRIBUTION (745), TOKEN_s_CET_FILEFORMAT (739), TOKEN_s_CET_LOCATION (738), TOKEN_s_CET_PERCENTAGE (744), TOKEN_s_CET_REJECTSAMPLEVALUE (742), TOKEN_s_CET_REJECTTYPE (740), TOKEN_s_CET_REJECTVALUE (741), TOKEN_s_CET_REMOTEOBJECTNAME (750), TOKEN_s_CET_REMOTESCHEMANAME (749), TOKEN_s_CET_REPLICATED (747), TOKEN_s_CET_ROUNDROBIN (748), TOKEN_s_CET_SHARDED (746), TOKEN_s_CET_VALUE (743), TOKEN_s_COLADDROPOPT_HIDDEN (537), TOKEN_s_COLADDROPOPT_MASKED (536), TOKEN_s_COLADDROPOPT_PERSISTED (534), TOKEN_s_COLADDROPOPT_SPARSE (535), TOKEN_s_COLDEFOPT_COLUMN_GENERATED (527), TOKEN_s_COLDEFOPT_COLUMN_SET (526), TOKEN_s_COLDEFOPT_ENCRYPTED (528), TOKEN_s_COLDEFOPT_FILESTREAM (529), TOKEN_s_COLDEFOPT_HIDDEN (531), TOKEN_s_COLDEFOPT_MASKED (530), TOKEN_s_COLDEFOPT_SPARSE (525), TOKEN_s_CREATEDB_COPY (468), TOKEN_s_CREATEDB_SNAP (467), TOKEN_s_CREATEDBOPT_CATALOGCOLLATION (462), TOKEN_s_CREATEDBOPT_FILESTREAM (461), TOKEN_s_CREATEDBOPT_OTHER (464), TOKEN_s_CREATEDBOPT_PERSISTENT_LOG_BUFFER (463), TOKEN_s_CTO_FEDERATED (666), TOKEN_s_CTO_FILESTREAM_ON (664), TOKEN_s_CTO_TEXTIMAGE_ON (665), TOKEN_s_CTW_DATA_COMPRESSION (669), TOKEN_s_CTW_DURABILITY (676), TOKEN_s_CTW_FFT_COLLATE_FILENAME (671), TOKEN_s_CTW_FFT_FILETABLE_DIRECTORY (670), TOKEN_s_CTW_FFT_FULLPATH_UNIQUE_CONSTRAINT_NAME (674), TOKEN_s_CTW_FFT_PRIMARY_KEY_CONSTRAINT_NAME (672), TOKEN_s_CTW_FFT_STREAMID_UNIQUE_CONSTRAINT_NAME (673), TOKEN_s_CTW_MEMORY_OPTIMIZED (675), TOKEN_s_CTW_REMOTE_DATA_ARCHIVE (678), TOKEN_s_CTW_SYSTEM_VERSIONING (677), TOKEN_s_CUW_PASSWORD (621), TOKEN_s_CUW_PROPERTY (623), TOKEN_s_CUW_USER_TYPE (622), TOKEN_s_DBSC_MAX_DOP (801), TOKEN_s_DBSC_ON_OFF_OPTION (802), TOKEN_s_DUMPOPT_ENCRYPTION (496), TOKEN_s_DUMPOPT_ENCRYPTION_ALGORITHM (500), TOKEN_s_DUMPOPT_ENCRYPTION_ASYMMETRIC (503), TOKEN_s_DUMPOPT_ENCRYPTION_CERTIFICATE (502), TOKEN_s_DUMPOPT_ENCRYPTION_SERVER (501), TOKEN_s_DUMPOPT_OTHER (497), TOKEN_s_EDGE_TYPE (806), TOKEN_s_epaff_CPU (595), TOKEN_s_epaff_NUMA (596), TOKEN_s_ET_DATASOURCE (759), TOKEN_s_ET_FILEFORMAT (760), TOKEN_s_ET_POOL (763), TOKEN_s_ET_RESOURCE (762), TOKEN_s_ET_TABLE (758), TOKEN_s_ET_URLFORMAT (761), TOKEN_s_FILETABLE (807), TOKEN_s_FP_LIST (613), TOKEN_s_FP_PROPERTY (612), TOKEN_s_FSD_DIRECTORY_NAME (661), TOKEN_s_FSD_NON_TRANSACTED_ACCESS (660), TOKEN_s_FTS_CATALOG (604), TOKEN_s_FTS_CHANGE_TRACKING (605), TOKEN_s_FTS_NO (608), TOKEN_s_FTS_POPULATION (606), TOKEN_s_FTS_SEARCH (609), TOKEN_s_FTS_STOPLIST (607), TOKEN_s_GEODR_CONNOPT (796), TOKEN_s_GEODR_REPLACE (797), TOKEN_s_GEODR_SRVOBJ (798), TOKEN_s_IA_ABORT (564), TOKEN_s_IA_DISABLE (562), TOKEN_s_IA_PAUSE (565), TOKEN_s_IA_REBUILD (560), TOKEN_s_IA_REORGANIZE (561), TOKEN_s_IA_RESUME (563), TOKEN_s_IDXSORTOPT_SORTED_DATA (521), TOKEN_s_IDXSORTOPT_SORTED_DATA_REORG (522), TOKEN_s_IIIS_COLUMNSTORE (695), TOKEN_s_IIIS_FILESTREAM_ON (696), TOKEN_s_IIIS_HASH (694), TOKEN_s_IO_BUCKETCOUNT (549), TOKEN_s_IO_COMPRESSION_DELAY (551), TOKEN_s_IO_DATACOMPRESSION (544), TOKEN_s_IO_DISTRIBUTION (548), TOKEN_s_IO_FILESTREAM_ON (554), TOKEN_s_IO_IGNORE_DUP_KEY (552), TOKEN_s_IO_MAX_DURATION (556), TOKEN_s_IO_MAXDOP (545), TOKEN_s_IO_MOVE (553), TOKEN_s_IO_ONLINE (550), TOKEN_s_IO_ONOFFOPTION (547), TOKEN_s_IO_RESUMABLE (555), TOKEN_s_IO_STATSONLY (546), TOKEN_s_IO_WAIT_AT_LOW_PRIORITY (557), TOKEN_s_LOADOPT_FILESTREAM (506), TOKEN_s_LOADOPT_OTHER (507), TOKEN_s_NODE_TYPE (805), TOKEN_s_OSI_COLUMN_SET (541), TOKEN_s_OSI_SPARSE (540), TOKEN_s_paff_NUMA (592), TOKEN_s_paff_SCHED (591), TOKEN_s_PARTITION (653), TOKEN_s_PERSISTENT_LOG_BUFFER_OPT_DIRECTORY_NAME (810), TOKEN_s_QDS_CAPTURE_MODE (769), TOKEN_s_QDS_CLEANUP_POLICY (768), TOKEN_s_QDS_DESIRED_STATE (766), TOKEN_s_QDS_FLUSH_INTERVAL (773), TOKEN_s_QDS_FLUSH_INTERVAL_SECONDS (772), TOKEN_s_QDS_INTERVAL_LENGTH (774), TOKEN_s_QDS_MAX_PLANS_PER_QUERY (775), TOKEN_s_QDS_MAX_SIZE_MB (771), TOKEN_s_QDS_OPERATION_MODE (767), TOKEN_s_QDS_SIZE_BASED_CLEANUP_MODE (770), TOKEN_s_REMOTE_DATA_ARCHIVE_DB_OPT_CREDENTIAL (779), TOKEN_s_REMOTE_DATA_ARCHIVE_DB_OPT_FEDERATED_SERVICE_ACCOUNT (780), TOKEN_s_REMOTE_DATA_ARCHIVE_DB_OPT_SERVER (778), TOKEN_s_seq_CACHE (579), TOKEN_s_seq_CYCLE (578), TOKEN_s_seq_INCREMENT (575), TOKEN_s_seq_MAXVALUE (577), TOKEN_s_seq_MINVALUE (576), TOKEN_s_seq_NO (580), TOKEN_s_seq_RESTART (573), TOKEN_s_seq_START (574), TOKEN_s_SP_AFTER (703), TOKEN_s_SP_BEFORE (702), TOKEN_s_SP_BLOCK (700), TOKEN_s_SP_FILTER (699), TOKEN_s_SP_PREDICATE (701), TOKEN_s_SV_DATA_CONSISTENCY_CHECK (682), TOKEN_s_SV_HISTORY_RETENTION_PERIOD (683), TOKEN_s_SV_HISTORY_TABLE (681), TOKEN_s_SXI_MAXLENGTH (690), TOKEN_s_SXI_SINGLETON (691), TOKEN_s_SXI_SQL (687), TOKEN_s_SXI_XQUERY (686), TOKEN_s_TABLOCKOPT_ABORT_AFTER_WAIT (518), TOKEN_s_TABLOCKOPT_MAX_DURATION (517), TOKEN_s_TABOPTNAME_FILESTREAM_ON (510), TOKEN_s_TABOPTNAME_FILETABLE_DIRECTORY (512), TOKEN_s_TABOPTNAME_LOCK_ESCALATION (511), TOKEN_s_TABOPTNAME_REMOTE_DATA_ARCHIVE (514), TOKEN_s_TABOPTNAME_SYSTEM_VERSIONING (513), TOKEN_s_UNBOUNDED (654), TOKEN_SAVE (287), TOKEN_SCHEMA (200), TOKEN_SELECT (288), TOKEN_SEMANTICKEYPHRASETABLE (390), TOKEN_SEMANTICSIMILARITYDETAILSTABLE (391), TOKEN_SEMANTICSIMILARITYTABLE (389), TOKEN_SESSION_USER (330), TOKEN_SET (149), TOKEN_SETUSER (289), TOKEN_SHUTDOWN (291), TOKEN_START_UPDATE (344), TOKEN_STATISTICS (292), TOKEN_STRING (176), TOKEN_SUB_EQ (191), TOKEN_SYSTEM_USER (331), TOKEN_TABLE (293), TOKEN_TABLESAMPLE (294), TOKEN_TEXT_LEX (178), TOKEN_TEXTSIZE (299), TOKEN_THEN (295), TOKEN_TO (296), TOKEN_TOP (336), TOKEN_TRAILING_DOT_NUMERIC (813), TOKEN_TRANSACTION (297), TOKEN_TRIGGER (298), TOKEN_TRUNCATE (300), TOKEN_TRY_CONVERT (222), TOKEN_TSEQUAL (263), TOKEN_UNION (157), TOKEN_UNIQUE (301), TOKEN_UNPIVOT (160), TOKEN_UPDATE (302), TOKEN_UPDATETEXT (303), TOKEN_USEDB (304), TOKEN_USER (328), TOKEN_VALUES (305), TOKEN_VARIABLE (175), TOKEN_VARYING (204), TOKEN_VIEW (306), TOKEN_WAITFOR (307), TOKEN_WHEN (309), TOKEN_WHERE (308), TOKEN_WHILE (310), TOKEN_WITH (141), TOKEN_WITH_CHECK (142), TOKEN_WITH_GB_HINT (392), TOKEN_WRITETEXT (311), TOKEN_X_DUMP (838), TOKEN_X_LOAD (839), TOKEN_X_TRANSACTION (840) """
    accumulators: Tokens = ...
    END_AFFINITY_TYPE_SUBTOKENS: Tokens = ...
    END_AFTER_BEGIN_SUBTOKENS: Tokens = ...
    END_AFTER_END_SUBTOKENS: Tokens = ...
    END_AFTER_FTS_WITH_SUBTOKENS: Tokens = ...
    END_AFTER_WITH_EXEC_OPTION_SUBTOKENS: Tokens = ...
    END_AFTER_WITH_SUBTOKENS: Tokens = ...
    END_AG_REPLICA_OPTION_SUBTOKENS: Tokens = ...
    END_ALTER_DB_OPT_SUBTOKENS: Tokens = ...
    END_ALTER_EXTERNALDATASOURCE_WITH_SUBTOKENS: Tokens = ...
    END_ALTER_SERVER_CONFIG_SET_DIAG_LOG_SUBTOKENS: Tokens = ...
    END_ALTER_SERVER_CONFIG_SET_HADR_CLUSTER_SUBTOKENS: Tokens = ...
    END_ALTER_SERVER_CONFIG_SET_SUBTOKENS: Tokens = ...
    END_ALTER_SERVER_TYPE_SUBTOKENS: Tokens = ...
    END_ALTER_USER_WITH_SUBTOKENS: Tokens = ...
    END_ALTTAB_ACTIONS_SUBTOKENS: Tokens = ...
    END_ALTTAB_ENABLE_DISABLE_SUBTOKENS: Tokens = ...
    END_COL_ADD_DROP_OPT_SUBTOKENS: Tokens = ...
    END_COL_DEF_OPT_SUBTOKENS: Tokens = ...
    END_COL_ENCRYPTION_OR_MASTER_KEY_SUBTOKENS: Tokens = ...
    END_CREATE_DB_OPT_SUBTOKENS: Tokens = ...
    END_CREATE_DB_TYPE_SUBTOKENS: Tokens = ...
    END_CREATE_DROP_ALTER_SUBTOKENS: Tokens = ...
    END_CREATE_EXTERNALDATASOURCE_WITH_SUBTOKENS: Tokens = ...
    END_CREATE_EXTERNALFILEFORMAT_WITH_SUBTOKENS: Tokens = ...
    END_CREATE_EXTERNALTABLE_WITH_SUBTOKENS: Tokens = ...
    END_CREATE_TAB_OPT_SUBTOKENS: Tokens = ...
    END_CREATE_TAB_WITH_OPT_SUBTOKENS: Tokens = ...
    END_CREATE_USER_WITH_SUBTOKENS: Tokens = ...
    END_DB_SCOPED_CONFIG_OPT_SUBTOKENS: Tokens = ...
    END_DEPRECATED_TOKENS: Tokens = ...
    END_DUMP_ENCRYPTION_OPT_SUBTOKENS: Tokens = ...
    END_DUMP_OPT_SUBTOKENS: Tokens = ...
    END_EXTERNAL_POOL_AFFINITY_TYPE_SUBTOKENS: Tokens = ...
    END_EXTERNAL_TYPE_SUBTOKENS: Tokens = ...
    END_FILESTREAM_DB_OPT_SUBTOKENS: Tokens = ...
    END_FTS_PROPERTY_SUBTOKENS: Tokens = ...
    END_FULLTEXT_SEARCH_SUBTOKENS: Tokens = ...
    END_GEODR_OPT_SUBTOKENS: Tokens = ...
    END_GRAPH_ID_OR_FILETABLE_SUBTOKENS: Tokens = ...
    END_INDEX_SORT_OPT_SUBTOKENS: Tokens = ...
    END_IND_ACTIONS_SUBTOKENS: Tokens = ...
    END_IND_OPTIONS_SUBTOKENS: Tokens = ...
    END_IN_INLINE_INDEX_SYNTAX_SUBTOKENS: Tokens = ...
    END_LEFT_PAREN_COMPAT_SUBTOKENS: Tokens = ...
    END_LOAD_OPT_SUBTOKENS: Tokens = ...
    END_MISSING_TOKENS: Tokens = ...
    END_OPT_STORAGE_ID_SUBTOKENS: Tokens = ...
    END_OPT_SXI_PATH_KIND_SUBTOKENS: Tokens = ...
    END_OPT_SXI_PATH_OPTION_SUBTOKENS: Tokens = ...
    END_OVER_CLAUSE_SUBTOKENS: Tokens = ...
    END_PERSISTENT_LOG_BUFFER_OPT_SUBTOKENS: Tokens = ...
    END_POOL_AFFINITY_TYPE_SUBTOKENS: Tokens = ...
    END_QUERY_STORE_OPT_SUBTOKENS: Tokens = ...
    END_REMOTE_DATA_ARCHIVE_OPT_SUBTOKENS: Tokens = ...
    END_SECURITY_POLICY_SUBTOKENS: Tokens = ...
    END_SEQUENCE_OPTIONS_SUBTOKENS: Tokens = ...
    END_SYSTEM_VERSIONING_OPT_SUBTOKENS: Tokens = ...
    END_TAB_LOCK_OPT_SUBTOKENS: Tokens = ...
    END_TAB_OPT_NAME_SUBTOKENS: Tokens = ...
    EOF: Tokens = ...
    error: Tokens = ...
    error_1_discard_max: Tokens = ...
    error_unlimited_discard: Tokens = ...
    Highest: Tokens = ...
    LAST_TOKEN: Tokens = ...
    LEX_ACCUMULATE_BINARY: Tokens = ...
    LEX_ACCUMULATE_ID: Tokens = ...
    LEX_ACCUMULATE_STRING: Tokens = ...
    LEX_BATCH_SEPERATOR: Tokens = ...
    LEX_END_OF_LINE_COMMENT: Tokens = ...
    LEX_ERROR: Tokens = ...
    LEX_MULTILINE_COMMENT: Tokens = ...
    LEX_WHITE: Tokens = ...
    lower_than_grant: Tokens = ...
    lower_than_left_paren: Tokens = ...
    Lowest: Tokens = ...
    maxParseToken: Tokens = ...
    NON_EMPTY: Tokens = ...
    SQL_CMD_MODE_TOKEN: Tokens = ...
    START_AFFINITY_TYPE_SUBTOKENS: Tokens = ...
    START_AFTER_BEGIN_SUBTOKENS: Tokens = ...
    START_AFTER_END_SUBTOKENS: Tokens = ...
    START_AFTER_FTS_WITH_SUBTOKENS: Tokens = ...
    START_AFTER_WITH_EXEC_OPTION_SUBTOKENS: Tokens = ...
    START_AFTER_WITH_SUBTOKENS: Tokens = ...
    START_AG_REPLICA_OPTION_SUBTOKENS: Tokens = ...
    START_ALTER_DB_OPT_SUBTOKENS: Tokens = ...
    START_ALTER_EXTERNALDATASOURCE_WITH_SUBTOKENS: Tokens = ...
    START_ALTER_SERVER_CONFIG_SET_DIAG_LOG_SUBTOKENS: Tokens = ...
    START_ALTER_SERVER_CONFIG_SET_HADR_CLUSTER_SUBTOKENS: Tokens = ...
    START_ALTER_SERVER_CONFIG_SET_SUBTOKENS: Tokens = ...
    START_ALTER_SERVER_TYPE_SUBTOKENS: Tokens = ...
    START_ALTER_USER_WITH_SUBTOKENS: Tokens = ...
    START_ALTTAB_ACTIONS_SUBTOKENS: Tokens = ...
    START_ALTTAB_ENABLE_DISABLE_SUBTOKENS: Tokens = ...
    START_COL_ADD_DROP_OPT_SUBTOKENS: Tokens = ...
    START_COL_DEF_OPT_SUBTOKENS: Tokens = ...
    START_COL_ENCRYPTION_OR_MASTER_KEY_SUBTOKENS: Tokens = ...
    START_CREATE_DB_OPT_SUBTOKENS: Tokens = ...
    START_CREATE_DB_TYPE_SUBTOKENS: Tokens = ...
    START_CREATE_DROP_ALTER_SUBTOKENS: Tokens = ...
    START_CREATE_EXTERNALDATASOURCE_WITH_SUBTOKENS: Tokens = ...
    START_CREATE_EXTERNALFILEFORMAT_WITH_SUBTOKENS: Tokens = ...
    START_CREATE_EXTERNALTABLE_WITH_SUBTOKENS: Tokens = ...
    START_CREATE_TAB_OPT_SUBTOKENS: Tokens = ...
    START_CREATE_TAB_WITH_OPT_SUBTOKENS: Tokens = ...
    START_CREATE_USER_WITH_SUBTOKENS: Tokens = ...
    START_DB_SCOPED_CONFIG_OPT_SUBTOKENS: Tokens = ...
    START_DEPRECATED_TOKENS: Tokens = ...
    START_DUMP_ENCRYPTION_OPT_SUBTOKENS: Tokens = ...
    START_DUMP_OPT_SUBTOKENS: Tokens = ...
    START_EXTERNAL_POOL_AFFINITY_TYPE_SUBTOKENS: Tokens = ...
    START_EXTERNAL_TYPE_SUBTOKENS: Tokens = ...
    START_FILESTREAM_DB_OPT_SUBTOKENS: Tokens = ...
    START_FTS_PROPERTY_SUBTOKENS: Tokens = ...
    START_FULLTEXT_SEARCH_SUBTOKENS: Tokens = ...
    START_GEODR_OPT_SUBTOKENS: Tokens = ...
    START_GRAPH_ID_OR_FILETABLE_SUBTOKENS: Tokens = ...
    START_INDEX_SORT_OPT_SUBTOKENS: Tokens = ...
    START_IND_ACTIONS_SUBTOKENS: Tokens = ...
    START_IND_OPTIONS_SUBTOKENS: Tokens = ...
    START_IN_INLINE_INDEX_SYNTAX_SUBTOKENS: Tokens = ...
    START_LEFT_PAREN_COMPAT_SUBTOKENS: Tokens = ...
    START_LOAD_OPT_SUBTOKENS: Tokens = ...
    START_MISSING_TOKENS: Tokens = ...
    START_OPT_STORAGE_ID_SUBTOKENS: Tokens = ...
    START_OPT_SXI_PATH_KIND_SUBTOKENS: Tokens = ...
    START_OPT_SXI_PATH_OPTION_SUBTOKENS: Tokens = ...
    START_OVER_CLAUSE_SUBTOKENS: Tokens = ...
    START_PERSISTENT_LOG_BUFFER_OPT_SUBTOKENS: Tokens = ...
    START_POOL_AFFINITY_TYPE_SUBTOKENS: Tokens = ...
    START_QUERY_STORE_OPT_SUBTOKENS: Tokens = ...
    START_REMOTE_DATA_ARCHIVE_OPT_SUBTOKENS: Tokens = ...
    START_SECURITY_POLICY_SUBTOKENS: Tokens = ...
    START_SEQUENCE_OPTIONS_SUBTOKENS: Tokens = ...
    START_SYSTEM_VERSIONING_OPT_SUBTOKENS: Tokens = ...
    START_TAB_LOCK_OPT_SUBTOKENS: Tokens = ...
    START_TAB_OPT_NAME_SUBTOKENS: Tokens = ...
    TOKEN_ADD: Tokens = ...
    TOKEN_ADD_EQ: Tokens = ...
    TOKEN_ALL: Tokens = ...
    TOKEN_ALTER: Tokens = ...
    TOKEN_AND: Tokens = ...
    TOKEN_ANY: Tokens = ...
    TOKEN_AS: Tokens = ...
    TOKEN_ASC: Tokens = ...
    TOKEN_AUDIT_SPECIFICATION: Tokens = ...
    TOKEN_AUTHORIZATION: Tokens = ...
    TOKEN_BEGIN: Tokens = ...
    TOKEN_BEGIN_CATCH: Tokens = ...
    TOKEN_BEGIN_CS: Tokens = ...
    TOKEN_BEGIN_TRY: Tokens = ...
    TOKEN_BETWEEN: Tokens = ...
    TOKEN_BINARY: Tokens = ...
    TOKEN_BREAK: Tokens = ...
    TOKEN_BROWSE: Tokens = ...
    TOKEN_BULK: Tokens = ...
    TOKEN_BW_AND_EQ: Tokens = ...
    TOKEN_BW_OR_EQ: Tokens = ...
    TOKEN_BW_XOR_EQ: Tokens = ...
    TOKEN_BY: Tokens = ...
    TOKEN_CASCADE: Tokens = ...
    TOKEN_CASE: Tokens = ...
    TOKEN_CHECK: Tokens = ...
    TOKEN_CHECKPOINT: Tokens = ...
    TOKEN_CLOSE: Tokens = ...
    TOKEN_CLUSTERED: Tokens = ...
    TOKEN_COALESCE: Tokens = ...
    TOKEN_COLLATE: Tokens = ...
    TOKEN_COLUMN: Tokens = ...
    TOKEN_COMMIT: Tokens = ...
    TOKEN_COMPUTE: Tokens = ...
    TOKEN_CONSTRAINT: Tokens = ...
    TOKEN_CONTAINS: Tokens = ...
    TOKEN_CONTAINSTABLE: Tokens = ...
    TOKEN_CONTINUE: Tokens = ...
    TOKEN_CONVERT: Tokens = ...
    TOKEN_CREATE: Tokens = ...
    TOKEN_CROSS: Tokens = ...
    TOKEN_CURRENT: Tokens = ...
    TOKEN_CURRENT_DATE: Tokens = ...
    TOKEN_CURRENT_TIME: Tokens = ...
    TOKEN_CURRENT_TIMESTAMP: Tokens = ...
    TOKEN_CURRENT_USER: Tokens = ...
    TOKEN_CURSOR: Tokens = ...
    TOKEN_c_ASSEMBLY: Tokens = ...
    TOKEN_c_ASYMMETRIC: Tokens = ...
    TOKEN_c_AT_TIME_ZONE: Tokens = ...
    TOKEN_c_CERT: Tokens = ...
    TOKEN_c_CONVERSATION: Tokens = ...
    TOKEN_c_COUNTERSIGNATURE: Tokens = ...
    TOKEN_c_CUBE: Tokens = ...
    TOKEN_c_DIALOG: Tokens = ...
    TOKEN_c_DISABLE: Tokens = ...
    TOKEN_c_ENABLE: Tokens = ...
    TOKEN_c_FOR_SYSTEM_TIME: Tokens = ...
    TOKEN_c_GET: Tokens = ...
    TOKEN_c_INCLUDE: Tokens = ...
    TOKEN_c_LOG: Tokens = ...
    TOKEN_c_LOGIN: Tokens = ...
    TOKEN_c_MASTER: Tokens = ...
    TOKEN_c_MATCH: Tokens = ...
    TOKEN_c_MOVE: Tokens = ...
    TOKEN_c_NAME: Tokens = ...
    TOKEN_c_NEXTVALUE: Tokens = ...
    TOKEN_c_OPENJSON: Tokens = ...
    TOKEN_c_QUEUE: Tokens = ...
    TOKEN_c_RECEIVE: Tokens = ...
    TOKEN_c_REVERT: Tokens = ...
    TOKEN_c_ROLLUP: Tokens = ...
    TOKEN_c_SEND: Tokens = ...
    TOKEN_c_SERVER: Tokens = ...
    TOKEN_c_SERVICE: Tokens = ...
    TOKEN_c_SIGNATURE: Tokens = ...
    TOKEN_c_SYMMETRIC: Tokens = ...
    TOKEN_c_THROW: Tokens = ...
    TOKEN_c_TYPE: Tokens = ...
    TOKEN_c_USING: Tokens = ...
    TOKEN_c_WITHIN_GROUP: Tokens = ...
    TOKEN_c_XMLSCHEMA: Tokens = ...
    TOKEN_DATABASE: Tokens = ...
    TOKEN_DBCC: Tokens = ...
    TOKEN_DB_SCOPED_CONFIG: Tokens = ...
    TOKEN_DB_SCOPED_CREDENTIAL: Tokens = ...
    TOKEN_DEALLOCATE: Tokens = ...
    TOKEN_DECLARE: Tokens = ...
    TOKEN_DEFAULT: Tokens = ...
    TOKEN_DELETE: Tokens = ...
    TOKEN_DENY: Tokens = ...
    TOKEN_DESC: Tokens = ...
    TOKEN_DISTINCT: Tokens = ...
    TOKEN_DISTRIBUTED: Tokens = ...
    TOKEN_DIV_EQ: Tokens = ...
    TOKEN_DOLLAR_PARTITION: Tokens = ...
    TOKEN_DOUBLE: Tokens = ...
    TOKEN_DOUBLECOLON: Tokens = ...
    TOKEN_DROP: Tokens = ...
    TOKEN_DUMP: Tokens = ...
    TOKEN_ELSE: Tokens = ...
    TOKEN_EMBEDED_DOT_NUMERIC: Tokens = ...
    TOKEN_ENCRYPTION_KEY: Tokens = ...
    TOKEN_END: Tokens = ...
    TOKEN_END_CS: Tokens = ...
    TOKEN_ERRLVL: Tokens = ...
    TOKEN_ESCAPE: Tokens = ...
    TOKEN_EXCEPT: Tokens = ...
    TOKEN_EXECUTE: Tokens = ...
    TOKEN_EXISTS: Tokens = ...
    TOKEN_EXIT: Tokens = ...
    TOKEN_EXTERNAL: Tokens = ...
    TOKEN_FETCH: Tokens = ...
    TOKEN_FILE: Tokens = ...
    TOKEN_FILLFACTOR: Tokens = ...
    TOKEN_FOR: Tokens = ...
    TOKEN_FOREIGN: Tokens = ...
    TOKEN_FREETEXT: Tokens = ...
    TOKEN_FREETEXTTABLE: Tokens = ...
    TOKEN_FROM: Tokens = ...
    TOKEN_FULL: Tokens = ...
    TOKEN_FUNCTION: Tokens = ...
    TOKEN_GLOBAL_VAR: Tokens = ...
    TOKEN_GOTO: Tokens = ...
    TOKEN_GRAMMAR_COMPUTED_COLS: Tokens = ...
    TOKEN_GRAMMAR_FILTERED_INDEXES: Tokens = ...
    TOKEN_GRAMMAR_FILTERED_INDEX_EXPR: Tokens = ...
    TOKEN_GRAMMAR_OPTION_CLAUSE: Tokens = ...
    TOKEN_GRAMMAR_RECOMPILE: Tokens = ...
    TOKEN_GRAMMAR_SECURITY_PREDICATE: Tokens = ...
    TOKEN_GRAMMAR_SPCURSORDML: Tokens = ...
    TOKEN_GRAMMAR_SPCURSOROPEN: Tokens = ...
    TOKEN_GRAMMAR_SPCURSOROPEN_PROC: Tokens = ...
    TOKEN_GRAMMAR_STANDARD_TSQL: Tokens = ...
    TOKEN_GRAMMAR_XEVENT_PREDICATE: Tokens = ...
    TOKEN_GRANT: Tokens = ...
    TOKEN_GROUP: Tokens = ...
    TOKEN_HAVING: Tokens = ...
    TOKEN_HOLDLOCK: Tokens = ...
    TOKEN_ID: Tokens = ...
    TOKEN_IDENTITY: Tokens = ...
    TOKEN_IDENTITYCOL: Tokens = ...
    TOKEN_IDENTITY_INSERT: Tokens = ...
    TOKEN_IF: Tokens = ...
    TOKEN_IMAGE: Tokens = ...
    TOKEN_IN: Tokens = ...
    TOKEN_INDEX: Tokens = ...
    TOKEN_INNER: Tokens = ...
    TOKEN_INSERT: Tokens = ...
    TOKEN_INTEGER: Tokens = ...
    TOKEN_INTERSECT: Tokens = ...
    TOKEN_INTO: Tokens = ...
    TOKEN_IS: Tokens = ...
    TOKEN_JOIN: Tokens = ...
    TOKEN_KEY: Tokens = ...
    TOKEN_KILL: Tokens = ...
    TOKEN_LABEL: Tokens = ...
    TOKEN_LEADING_DOT_NUMERIC: Tokens = ...
    TOKEN_LEFT: Tokens = ...
    TOKEN_LEFT_PAREN_80: Tokens = ...
    TOKEN_LEFT_PAREN_90: Tokens = ...
    TOKEN_LIKE: Tokens = ...
    TOKEN_LINENO: Tokens = ...
    TOKEN_LOAD: Tokens = ...
    TOKEN_LOG_ON: Tokens = ...
    TOKEN_MERGE: Tokens = ...
    TOKEN_MISSING_AND: Tokens = ...
    TOKEN_MISSING_BEGIN_CATCH: Tokens = ...
    TOKEN_MISSING_CATCH: Tokens = ...
    TOKEN_MISSING_COMMA: Tokens = ...
    TOKEN_MISSING_END: Tokens = ...
    TOKEN_MISSING_EQUAL: Tokens = ...
    TOKEN_MISSING_INSERT_SOURCE: Tokens = ...
    TOKEN_MISSING_LITERAL: Tokens = ...
    TOKEN_MISSING_ON: Tokens = ...
    TOKEN_MISSING_RIGHT_PAREN: Tokens = ...
    TOKEN_MISSING_SET: Tokens = ...
    TOKEN_MISSING_SQLID: Tokens = ...
    TOKEN_MISSING_STRING_VAR: Tokens = ...
    TOKEN_MISSING_THEN: Tokens = ...
    TOKEN_MISSING_TRY: Tokens = ...
    TOKEN_MISSING_VARIABLE: Tokens = ...
    TOKEN_MISSING_WHEN: Tokens = ...
    TOKEN_MOD_EQ: Tokens = ...
    TOKEN_MONEY: Tokens = ...
    TOKEN_MULT_EQ: Tokens = ...
    TOKEN_NATIONAL: Tokens = ...
    TOKEN_NOCHECK: Tokens = ...
    TOKEN_NONCLUSTERED: Tokens = ...
    TOKEN_NOT: Tokens = ...
    TOKEN_NOT_FOR: Tokens = ...
    TOKEN_NULL: Tokens = ...
    TOKEN_NULLIF: Tokens = ...
    TOKEN_NUMERIC: Tokens = ...
    TOKEN_ODBC_PREFIX: Tokens = ...
    TOKEN_ODBC_TERMINATOR: Tokens = ...
    TOKEN_OF: Tokens = ...
    TOKEN_OFF: Tokens = ...
    TOKEN_OFFSETS: Tokens = ...
    TOKEN_ON: Tokens = ...
    TOKEN_OPEN: Tokens = ...
    TOKEN_OPENDATASOURCE: Tokens = ...
    TOKEN_OPENQUERY: Tokens = ...
    TOKEN_OPENROWSET: Tokens = ...
    TOKEN_OPENXML: Tokens = ...
    TOKEN_OPTION: Tokens = ...
    TOKEN_OR: Tokens = ...
    TOKEN_ORDER: Tokens = ...
    TOKEN_OUTER: Tokens = ...
    TOKEN_OVER: Tokens = ...
    TOKEN_PERCENT: Tokens = ...
    TOKEN_PIVOT: Tokens = ...
    TOKEN_PLAN: Tokens = ...
    TOKEN_PRIMARY: Tokens = ...
    TOKEN_PRINT: Tokens = ...
    TOKEN_PROCEDURE: Tokens = ...
    TOKEN_PROC_SEMI: Tokens = ...
    TOKEN_PSEUDOCOL: Tokens = ...
    TOKEN_PUBLIC: Tokens = ...
    TOKEN_QUOTED_ID: Tokens = ...
    TOKEN_RAISERROR: Tokens = ...
    TOKEN_READ: Tokens = ...
    TOKEN_READTEXT: Tokens = ...
    TOKEN_REAL: Tokens = ...
    TOKEN_RECONFIGURE: Tokens = ...
    TOKEN_REFERENCES: Tokens = ...
    TOKEN_REPLICATION: Tokens = ...
    TOKEN_REQJOIN: Tokens = ...
    TOKEN_RESTRICT: Tokens = ...
    TOKEN_RETURN: Tokens = ...
    TOKEN_REVERT: Tokens = ...
    TOKEN_REVOKE: Tokens = ...
    TOKEN_RIGHT: Tokens = ...
    TOKEN_ROLLBACK: Tokens = ...
    TOKEN_ROWCOUNT: Tokens = ...
    TOKEN_ROWGUIDCOL: Tokens = ...
    TOKEN_RULE: Tokens = ...
    TOKEN_SAVE: Tokens = ...
    TOKEN_SCHEMA: Tokens = ...
    TOKEN_SELECT: Tokens = ...
    TOKEN_SEMANTICKEYPHRASETABLE: Tokens = ...
    TOKEN_SEMANTICSIMILARITYDETAILSTABLE: Tokens = ...
    TOKEN_SEMANTICSIMILARITYTABLE: Tokens = ...
    TOKEN_SESSION_USER: Tokens = ...
    TOKEN_SET: Tokens = ...
    TOKEN_SETUSER: Tokens = ...
    TOKEN_SHUTDOWN: Tokens = ...
    TOKEN_START_UPDATE: Tokens = ...
    TOKEN_STATISTICS: Tokens = ...
    TOKEN_STRING: Tokens = ...
    TOKEN_SUB_EQ: Tokens = ...
    TOKEN_SYSTEM_USER: Tokens = ...
    TOKEN_s_AB_ATOMIC: Tokens = ...
    TOKEN_s_AEDS_CREDENTIAL: Tokens = ...
    TOKEN_s_AEDS_LOCATION: Tokens = ...
    TOKEN_s_AEDS_RESOURCEMANAGERLOCATION: Tokens = ...
    TOKEN_s_AE_CATCH: Tokens = ...
    TOKEN_s_AE_CONVERSATION: Tokens = ...
    TOKEN_s_AE_TRY: Tokens = ...
    TOKEN_s_aff_CPU: Tokens = ...
    TOKEN_s_aff_NUMA: Tokens = ...
    TOKEN_s_AFW_PROPERTY_DESCRIPTION: Tokens = ...
    TOKEN_s_AFW_PROPERTY_INT_ID: Tokens = ...
    TOKEN_s_AFW_PROPERTY_SET_GUID: Tokens = ...
    TOKEN_s_AG_ROLE_AGNOSTIC_OPTION: Tokens = ...
    TOKEN_s_AG_ROLE_SPECIFIC_OPTION: Tokens = ...
    TOKEN_s_ALTDBOPT_AUTO_CRT_STATS: Tokens = ...
    TOKEN_s_ALTDBOPT_CHANGE_TRACKING: Tokens = ...
    TOKEN_s_ALTDBOPT_CONTAINEDDB: Tokens = ...
    TOKEN_s_ALTDBOPT_DELAYED_DURABILITY: Tokens = ...
    TOKEN_s_ALTDBOPT_DIST_POLICY: Tokens = ...
    TOKEN_s_ALTDBOPT_failover: Tokens = ...
    TOKEN_s_ALTDBOPT_filegroup: Tokens = ...
    TOKEN_s_ALTDBOPT_FILESTREAM: Tokens = ...
    TOKEN_s_ALTDBOPT_force_failover: Tokens = ...
    TOKEN_s_ALTDBOPT_HADR: Tokens = ...
    TOKEN_s_ALTDBOPT_HARDENING: Tokens = ...
    TOKEN_s_ALTDBOPT_log: Tokens = ...
    TOKEN_s_ALTDBOPT_modify: Tokens = ...
    TOKEN_s_ALTDBOPT_name: Tokens = ...
    TOKEN_s_ALTDBOPT_OTHER: Tokens = ...
    TOKEN_s_ALTDBOPT_PERSISTENT_LOG_BUFFER: Tokens = ...
    TOKEN_s_ALTDBOPT_QUERY_STORE: Tokens = ...
    TOKEN_s_ALTDBOPT_rebuild: Tokens = ...
    TOKEN_s_ALTDBOPT_RECOVERY: Tokens = ...
    TOKEN_s_ALTDBOPT_REMOTE_DATA_ARCHIVE: Tokens = ...
    TOKEN_s_ALTDBOPT_remove: Tokens = ...
    TOKEN_s_ALTDBOPT_SECONDARY: Tokens = ...
    TOKEN_s_ALTDBOPT_TEMPORAL_RETENTION: Tokens = ...
    TOKEN_s_altserv_AUDIT: Tokens = ...
    TOKEN_s_altserv_CONFIG: Tokens = ...
    TOKEN_s_altserv_config_set_BUFFER_POOL_EXTENSION: Tokens = ...
    TOKEN_s_altserv_config_set_diaglog_MAX_FILES: Tokens = ...
    TOKEN_s_altserv_config_set_diaglog_MAX_SIZE: Tokens = ...
    TOKEN_s_altserv_config_set_diaglog_OFF: Tokens = ...
    TOKEN_s_altserv_config_set_diaglog_ON: Tokens = ...
    TOKEN_s_altserv_config_set_diaglog_PATH: Tokens = ...
    TOKEN_s_altserv_config_set_DIAGNOSTICS: Tokens = ...
    TOKEN_s_altserv_config_set_FAILOVER: Tokens = ...
    TOKEN_s_altserv_config_set_HADR: Tokens = ...
    TOKEN_s_altserv_config_set_hadr_cluster_CONTEXT: Tokens = ...
    TOKEN_s_altserv_config_set_PROCESS: Tokens = ...
    TOKEN_s_altserv_config_set_SOFTNUMA: Tokens = ...
    TOKEN_s_altserv_ROLE: Tokens = ...
    TOKEN_s_ALTTAB_DISABLE_ENABLE: Tokens = ...
    TOKEN_s_ALTTAB_EN_CHANGE_TRACKING: Tokens = ...
    TOKEN_s_ALTTAB_EN_FILETABLE_NAMESPACE: Tokens = ...
    TOKEN_s_ALTTAB_REBUILD: Tokens = ...
    TOKEN_s_ALTTAB_SWITCH: Tokens = ...
    TOKEN_s_AUW_PASSWORD: Tokens = ...
    TOKEN_s_AUW_PROPERTY: Tokens = ...
    TOKEN_s_AUW_SID: Tokens = ...
    TOKEN_s_AWEO_RECOMPILE: Tokens = ...
    TOKEN_s_AWEO_RESULT: Tokens = ...
    TOKEN_s_AW_CHANGE_TRACKING_CONTEXT: Tokens = ...
    TOKEN_s_AW_ID: Tokens = ...
    TOKEN_s_AW_XMLNAMESPACES: Tokens = ...
    TOKEN_s_CDA_AGGREGATE: Tokens = ...
    TOKEN_s_CDA_APPLICATION: Tokens = ...
    TOKEN_s_CDA_ASSEMBLY: Tokens = ...
    TOKEN_s_CDA_ASYMMETRIC: Tokens = ...
    TOKEN_s_CDA_AUDIT: Tokens = ...
    TOKEN_s_CDA_AVAILABILITY: Tokens = ...
    TOKEN_s_CDA_BROKER: Tokens = ...
    TOKEN_s_CDA_CERT: Tokens = ...
    TOKEN_s_CDA_COLUMNSTORE: Tokens = ...
    TOKEN_s_CDA_CONTRACT: Tokens = ...
    TOKEN_s_CDA_COUNTER: Tokens = ...
    TOKEN_s_CDA_CREDENTIAL: Tokens = ...
    TOKEN_s_CDA_CRYPTOGRAPHIC: Tokens = ...
    TOKEN_s_CDA_ENDPOINT: Tokens = ...
    TOKEN_s_CDA_EVENT: Tokens = ...
    TOKEN_s_CDA_FULLTEXT: Tokens = ...
    TOKEN_s_CDA_GOVERNOR: Tokens = ...
    TOKEN_s_CDA_LOGIN: Tokens = ...
    TOKEN_s_CDA_MASTER: Tokens = ...
    TOKEN_s_CDA_MESSAGE: Tokens = ...
    TOKEN_s_CDA_NOTIFICATION: Tokens = ...
    TOKEN_s_CDA_PARTITION: Tokens = ...
    TOKEN_s_CDA_POLICY: Tokens = ...
    TOKEN_s_CDA_POOL: Tokens = ...
    TOKEN_s_CDA_QUEUE: Tokens = ...
    TOKEN_s_CDA_REMOTE: Tokens = ...
    TOKEN_s_CDA_RESOURCE: Tokens = ...
    TOKEN_s_CDA_ROLE: Tokens = ...
    TOKEN_s_CDA_ROUTE: Tokens = ...
    TOKEN_s_CDA_SEARCH: Tokens = ...
    TOKEN_s_CDA_SECURITY: Tokens = ...
    TOKEN_s_CDA_SELECTIVE: Tokens = ...
    TOKEN_s_CDA_SEQUENCE: Tokens = ...
    TOKEN_s_CDA_SERVER: Tokens = ...
    TOKEN_s_CDA_SERVICE: Tokens = ...
    TOKEN_s_CDA_SESSION: Tokens = ...
    TOKEN_s_CDA_SIGNATURE: Tokens = ...
    TOKEN_s_CDA_SPATIAL: Tokens = ...
    TOKEN_s_CDA_SYMMETRIC: Tokens = ...
    TOKEN_s_CDA_SYNONYM: Tokens = ...
    TOKEN_s_CDA_TARGET: Tokens = ...
    TOKEN_s_CDA_TYPE: Tokens = ...
    TOKEN_s_CDA_WORKLOAD: Tokens = ...
    TOKEN_s_CDA_XML: Tokens = ...
    TOKEN_s_CEDS_CREDENTIAL: Tokens = ...
    TOKEN_s_CEDS_DATABASENAME: Tokens = ...
    TOKEN_s_CEDS_HADOOP: Tokens = ...
    TOKEN_s_CEDS_JOBTRACKERLOCATION: Tokens = ...
    TOKEN_s_CEDS_LOCATION: Tokens = ...
    TOKEN_s_CEDS_RDBMS: Tokens = ...
    TOKEN_s_CEDS_RESOURCEMANAGERLOCATION: Tokens = ...
    TOKEN_s_CEDS_SHARDMAPMANAGER: Tokens = ...
    TOKEN_s_CEDS_SHARDMAPNAME: Tokens = ...
    TOKEN_s_CEDS_SHAREDMEMORY: Tokens = ...
    TOKEN_s_CEDS_TYPE: Tokens = ...
    TOKEN_s_CEFF_DATA_COMPRESSION: Tokens = ...
    TOKEN_s_CEFF_DATEFORMAT: Tokens = ...
    TOKEN_s_CEFF_DELIMITEDTEXT: Tokens = ...
    TOKEN_s_CEFF_ENCODING: Tokens = ...
    TOKEN_s_CEFF_FALSE: Tokens = ...
    TOKEN_s_CEFF_FIELDTERMINATOR: Tokens = ...
    TOKEN_s_CEFF_FORMAT_OPTIONS: Tokens = ...
    TOKEN_s_CEFF_FORMAT_TYPE: Tokens = ...
    TOKEN_s_CEFF_ORC: Tokens = ...
    TOKEN_s_CEFF_PARQUET: Tokens = ...
    TOKEN_s_CEFF_RCFILE: Tokens = ...
    TOKEN_s_CEFF_ROWTERMINATOR: Tokens = ...
    TOKEN_s_CEFF_SERDEMETHOD: Tokens = ...
    TOKEN_s_CEFF_STRINGDELIMITER: Tokens = ...
    TOKEN_s_CEFF_TRUE: Tokens = ...
    TOKEN_s_CEFF_USETYPEDEFAULT: Tokens = ...
    TOKEN_s_CEMK_ALGORITHM: Tokens = ...
    TOKEN_s_CEMK_COL_ENCRYPTION_KEY: Tokens = ...
    TOKEN_s_CEMK_COL_MASTER_KEY: Tokens = ...
    TOKEN_s_CEMK_ENCRYPTED_VAL: Tokens = ...
    TOKEN_s_CEMK_ENCRYPTION: Tokens = ...
    TOKEN_s_CEMK_ENCRYPTION_TYPE: Tokens = ...
    TOKEN_s_CEMK_KEYSTORETYPE: Tokens = ...
    TOKEN_s_CEMK_MASTER: Tokens = ...
    TOKEN_s_CEMK_PATH: Tokens = ...
    TOKEN_s_CEMK_PROVIDER_NAME: Tokens = ...
    TOKEN_s_CEMK_VALUE: Tokens = ...
    TOKEN_s_CET_DATASOURCE: Tokens = ...
    TOKEN_s_CET_DISTRIBUTION: Tokens = ...
    TOKEN_s_CET_FILEFORMAT: Tokens = ...
    TOKEN_s_CET_LOCATION: Tokens = ...
    TOKEN_s_CET_PERCENTAGE: Tokens = ...
    TOKEN_s_CET_REJECTSAMPLEVALUE: Tokens = ...
    TOKEN_s_CET_REJECTTYPE: Tokens = ...
    TOKEN_s_CET_REJECTVALUE: Tokens = ...
    TOKEN_s_CET_REMOTEOBJECTNAME: Tokens = ...
    TOKEN_s_CET_REMOTESCHEMANAME: Tokens = ...
    TOKEN_s_CET_REPLICATED: Tokens = ...
    TOKEN_s_CET_ROUNDROBIN: Tokens = ...
    TOKEN_s_CET_SHARDED: Tokens = ...
    TOKEN_s_CET_VALUE: Tokens = ...
    TOKEN_s_COLADDROPOPT_HIDDEN: Tokens = ...
    TOKEN_s_COLADDROPOPT_MASKED: Tokens = ...
    TOKEN_s_COLADDROPOPT_PERSISTED: Tokens = ...
    TOKEN_s_COLADDROPOPT_SPARSE: Tokens = ...
    TOKEN_s_COLDEFOPT_COLUMN_GENERATED: Tokens = ...
    TOKEN_s_COLDEFOPT_COLUMN_SET: Tokens = ...
    TOKEN_s_COLDEFOPT_ENCRYPTED: Tokens = ...
    TOKEN_s_COLDEFOPT_FILESTREAM: Tokens = ...
    TOKEN_s_COLDEFOPT_HIDDEN: Tokens = ...
    TOKEN_s_COLDEFOPT_MASKED: Tokens = ...
    TOKEN_s_COLDEFOPT_SPARSE: Tokens = ...
    TOKEN_s_CREATEDBOPT_CATALOGCOLLATION: Tokens = ...
    TOKEN_s_CREATEDBOPT_FILESTREAM: Tokens = ...
    TOKEN_s_CREATEDBOPT_OTHER: Tokens = ...
    TOKEN_s_CREATEDBOPT_PERSISTENT_LOG_BUFFER: Tokens = ...
    TOKEN_s_CREATEDB_COPY: Tokens = ...
    TOKEN_s_CREATEDB_SNAP: Tokens = ...
    TOKEN_s_CTO_FEDERATED: Tokens = ...
    TOKEN_s_CTO_FILESTREAM_ON: Tokens = ...
    TOKEN_s_CTO_TEXTIMAGE_ON: Tokens = ...
    TOKEN_s_CTW_DATA_COMPRESSION: Tokens = ...
    TOKEN_s_CTW_DURABILITY: Tokens = ...
    TOKEN_s_CTW_FFT_COLLATE_FILENAME: Tokens = ...
    TOKEN_s_CTW_FFT_FILETABLE_DIRECTORY: Tokens = ...
    TOKEN_s_CTW_FFT_FULLPATH_UNIQUE_CONSTRAINT_NAME: Tokens = ...
    TOKEN_s_CTW_FFT_PRIMARY_KEY_CONSTRAINT_NAME: Tokens = ...
    TOKEN_s_CTW_FFT_STREAMID_UNIQUE_CONSTRAINT_NAME: Tokens = ...
    TOKEN_s_CTW_MEMORY_OPTIMIZED: Tokens = ...
    TOKEN_s_CTW_REMOTE_DATA_ARCHIVE: Tokens = ...
    TOKEN_s_CTW_SYSTEM_VERSIONING: Tokens = ...
    TOKEN_s_CUW_PASSWORD: Tokens = ...
    TOKEN_s_CUW_PROPERTY: Tokens = ...
    TOKEN_s_CUW_USER_TYPE: Tokens = ...
    TOKEN_s_DBSC_MAX_DOP: Tokens = ...
    TOKEN_s_DBSC_ON_OFF_OPTION: Tokens = ...
    TOKEN_s_DUMPOPT_ENCRYPTION: Tokens = ...
    TOKEN_s_DUMPOPT_ENCRYPTION_ALGORITHM: Tokens = ...
    TOKEN_s_DUMPOPT_ENCRYPTION_ASYMMETRIC: Tokens = ...
    TOKEN_s_DUMPOPT_ENCRYPTION_CERTIFICATE: Tokens = ...
    TOKEN_s_DUMPOPT_ENCRYPTION_SERVER: Tokens = ...
    TOKEN_s_DUMPOPT_OTHER: Tokens = ...
    TOKEN_s_EDGE_TYPE: Tokens = ...
    TOKEN_s_epaff_CPU: Tokens = ...
    TOKEN_s_epaff_NUMA: Tokens = ...
    TOKEN_s_ET_DATASOURCE: Tokens = ...
    TOKEN_s_ET_FILEFORMAT: Tokens = ...
    TOKEN_s_ET_POOL: Tokens = ...
    TOKEN_s_ET_RESOURCE: Tokens = ...
    TOKEN_s_ET_TABLE: Tokens = ...
    TOKEN_s_ET_URLFORMAT: Tokens = ...
    TOKEN_s_FILETABLE: Tokens = ...
    TOKEN_s_FP_LIST: Tokens = ...
    TOKEN_s_FP_PROPERTY: Tokens = ...
    TOKEN_s_FSD_DIRECTORY_NAME: Tokens = ...
    TOKEN_s_FSD_NON_TRANSACTED_ACCESS: Tokens = ...
    TOKEN_s_FTS_CATALOG: Tokens = ...
    TOKEN_s_FTS_CHANGE_TRACKING: Tokens = ...
    TOKEN_s_FTS_NO: Tokens = ...
    TOKEN_s_FTS_POPULATION: Tokens = ...
    TOKEN_s_FTS_SEARCH: Tokens = ...
    TOKEN_s_FTS_STOPLIST: Tokens = ...
    TOKEN_s_GEODR_CONNOPT: Tokens = ...
    TOKEN_s_GEODR_REPLACE: Tokens = ...
    TOKEN_s_GEODR_SRVOBJ: Tokens = ...
    TOKEN_s_IA_ABORT: Tokens = ...
    TOKEN_s_IA_DISABLE: Tokens = ...
    TOKEN_s_IA_PAUSE: Tokens = ...
    TOKEN_s_IA_REBUILD: Tokens = ...
    TOKEN_s_IA_REORGANIZE: Tokens = ...
    TOKEN_s_IA_RESUME: Tokens = ...
    TOKEN_s_IDXSORTOPT_SORTED_DATA: Tokens = ...
    TOKEN_s_IDXSORTOPT_SORTED_DATA_REORG: Tokens = ...
    TOKEN_s_IIIS_COLUMNSTORE: Tokens = ...
    TOKEN_s_IIIS_FILESTREAM_ON: Tokens = ...
    TOKEN_s_IIIS_HASH: Tokens = ...
    TOKEN_s_IO_BUCKETCOUNT: Tokens = ...
    TOKEN_s_IO_COMPRESSION_DELAY: Tokens = ...
    TOKEN_s_IO_DATACOMPRESSION: Tokens = ...
    TOKEN_s_IO_DISTRIBUTION: Tokens = ...
    TOKEN_s_IO_FILESTREAM_ON: Tokens = ...
    TOKEN_s_IO_IGNORE_DUP_KEY: Tokens = ...
    TOKEN_s_IO_MAXDOP: Tokens = ...
    TOKEN_s_IO_MAX_DURATION: Tokens = ...
    TOKEN_s_IO_MOVE: Tokens = ...
    TOKEN_s_IO_ONLINE: Tokens = ...
    TOKEN_s_IO_ONOFFOPTION: Tokens = ...
    TOKEN_s_IO_RESUMABLE: Tokens = ...
    TOKEN_s_IO_STATSONLY: Tokens = ...
    TOKEN_s_IO_WAIT_AT_LOW_PRIORITY: Tokens = ...
    TOKEN_s_LOADOPT_FILESTREAM: Tokens = ...
    TOKEN_s_LOADOPT_OTHER: Tokens = ...
    TOKEN_s_NODE_TYPE: Tokens = ...
    TOKEN_s_OSI_COLUMN_SET: Tokens = ...
    TOKEN_s_OSI_SPARSE: Tokens = ...
    TOKEN_s_paff_NUMA: Tokens = ...
    TOKEN_s_paff_SCHED: Tokens = ...
    TOKEN_s_PARTITION: Tokens = ...
    TOKEN_s_PERSISTENT_LOG_BUFFER_OPT_DIRECTORY_NAME: Tokens = ...
    TOKEN_s_QDS_CAPTURE_MODE: Tokens = ...
    TOKEN_s_QDS_CLEANUP_POLICY: Tokens = ...
    TOKEN_s_QDS_DESIRED_STATE: Tokens = ...
    TOKEN_s_QDS_FLUSH_INTERVAL: Tokens = ...
    TOKEN_s_QDS_FLUSH_INTERVAL_SECONDS: Tokens = ...
    TOKEN_s_QDS_INTERVAL_LENGTH: Tokens = ...
    TOKEN_s_QDS_MAX_PLANS_PER_QUERY: Tokens = ...
    TOKEN_s_QDS_MAX_SIZE_MB: Tokens = ...
    TOKEN_s_QDS_OPERATION_MODE: Tokens = ...
    TOKEN_s_QDS_SIZE_BASED_CLEANUP_MODE: Tokens = ...
    TOKEN_s_REMOTE_DATA_ARCHIVE_DB_OPT_CREDENTIAL: Tokens = ...
    TOKEN_s_REMOTE_DATA_ARCHIVE_DB_OPT_FEDERATED_SERVICE_ACCOUNT: Tokens = ...
    TOKEN_s_REMOTE_DATA_ARCHIVE_DB_OPT_SERVER: Tokens = ...
    TOKEN_s_seq_CACHE: Tokens = ...
    TOKEN_s_seq_CYCLE: Tokens = ...
    TOKEN_s_seq_INCREMENT: Tokens = ...
    TOKEN_s_seq_MAXVALUE: Tokens = ...
    TOKEN_s_seq_MINVALUE: Tokens = ...
    TOKEN_s_seq_NO: Tokens = ...
    TOKEN_s_seq_RESTART: Tokens = ...
    TOKEN_s_seq_START: Tokens = ...
    TOKEN_s_SP_AFTER: Tokens = ...
    TOKEN_s_SP_BEFORE: Tokens = ...
    TOKEN_s_SP_BLOCK: Tokens = ...
    TOKEN_s_SP_FILTER: Tokens = ...
    TOKEN_s_SP_PREDICATE: Tokens = ...
    TOKEN_s_SV_DATA_CONSISTENCY_CHECK: Tokens = ...
    TOKEN_s_SV_HISTORY_RETENTION_PERIOD: Tokens = ...
    TOKEN_s_SV_HISTORY_TABLE: Tokens = ...
    TOKEN_s_SXI_MAXLENGTH: Tokens = ...
    TOKEN_s_SXI_SINGLETON: Tokens = ...
    TOKEN_s_SXI_SQL: Tokens = ...
    TOKEN_s_SXI_XQUERY: Tokens = ...
    TOKEN_s_TABLOCKOPT_ABORT_AFTER_WAIT: Tokens = ...
    TOKEN_s_TABLOCKOPT_MAX_DURATION: Tokens = ...
    TOKEN_s_TABOPTNAME_FILESTREAM_ON: Tokens = ...
    TOKEN_s_TABOPTNAME_FILETABLE_DIRECTORY: Tokens = ...
    TOKEN_s_TABOPTNAME_LOCK_ESCALATION: Tokens = ...
    TOKEN_s_TABOPTNAME_REMOTE_DATA_ARCHIVE: Tokens = ...
    TOKEN_s_TABOPTNAME_SYSTEM_VERSIONING: Tokens = ...
    TOKEN_s_UNBOUNDED: Tokens = ...
    TOKEN_TABLE: Tokens = ...
    TOKEN_TABLESAMPLE: Tokens = ...
    TOKEN_TEXTSIZE: Tokens = ...
    TOKEN_TEXT_LEX: Tokens = ...
    TOKEN_THEN: Tokens = ...
    TOKEN_TO: Tokens = ...
    TOKEN_TOP: Tokens = ...
    TOKEN_TRAILING_DOT_NUMERIC: Tokens = ...
    TOKEN_TRANSACTION: Tokens = ...
    TOKEN_TRIGGER: Tokens = ...
    TOKEN_TRUNCATE: Tokens = ...
    TOKEN_TRY_CONVERT: Tokens = ...
    TOKEN_TSEQUAL: Tokens = ...
    TOKEN_UNION: Tokens = ...
    TOKEN_UNIQUE: Tokens = ...
    TOKEN_UNPIVOT: Tokens = ...
    TOKEN_UPDATE: Tokens = ...
    TOKEN_UPDATETEXT: Tokens = ...
    TOKEN_USEDB: Tokens = ...
    TOKEN_USER: Tokens = ...
    TOKEN_VALUES: Tokens = ...
    TOKEN_VARIABLE: Tokens = ...
    TOKEN_VARYING: Tokens = ...
    TOKEN_VIEW: Tokens = ...
    TOKEN_WAITFOR: Tokens = ...
    TOKEN_WHEN: Tokens = ...
    TOKEN_WHERE: Tokens = ...
    TOKEN_WHILE: Tokens = ...
    TOKEN_WITH: Tokens = ...
    TOKEN_WITH_CHECK: Tokens = ...
    TOKEN_WITH_GB_HINT: Tokens = ...
    TOKEN_WRITETEXT: Tokens = ...
    TOKEN_X_DUMP: Tokens = ...
    TOKEN_X_LOAD: Tokens = ...
    TOKEN_X_TRANSACTION: Tokens = ...
    value__ = ...


# variables with complex values

