# encoding: utf-8
# module System.Web.Security.AntiXss calls itself AntiXss
# from System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
# by generator 1.145
""" no doc """
from __future__ import annotations
from System import Enum

from System.Web.Util import HttpEncoder

"""The following names are not found in the module: field#
"""

# no functions
# classes

class AntiXssEncoder(HttpEncoder): # skipped bases: <type 'object'>
    """ AntiXssEncoder() """
    @staticmethod
    def CssEncode(input:str) -> str:
        """ CssEncode(input: str) -> str """
        ...

    @staticmethod
    def HtmlFormUrlEncode(input:str, *__args:int) -> str:
        """
        HtmlFormUrlEncode(input: str) -> str
        HtmlFormUrlEncode(input: str, codePage: int) -> str
        HtmlFormUrlEncode(input: str, inputEncoding: Encoding) -> str
        """
        ...

    @staticmethod
    def MarkAsSafe(lowerCodeCharts:LowerCodeCharts, lowerMidCodeCharts:LowerMidCodeCharts, midCodeCharts:MidCodeCharts, upperMidCodeCharts:UpperMidCodeCharts, upperCodeCharts:UpperCodeCharts): # -> 
        """ MarkAsSafe(lowerCodeCharts: LowerCodeCharts, lowerMidCodeCharts: LowerMidCodeCharts, midCodeCharts: MidCodeCharts, upperMidCodeCharts: UpperMidCodeCharts, upperCodeCharts: UpperCodeCharts) """
        ...

    @staticmethod
    def XmlAttributeEncode(input:str) -> str:
        """ XmlAttributeEncode(input: str) -> str """
        ...

    @staticmethod
    def XmlEncode(input:str) -> str:
        """ XmlEncode(input: str) -> str """
        ...


class LowerCodeCharts(Enum): # skipped bases: <type 'IFormattable'>, <type 'IConvertible'>, <type 'IComparable'>, <type 'object'>
    """ enum (flags) LowerCodeCharts, values: Arabic (4096), ArabicSupplement (16384), Armenian (1024), BasicLatin (1), Bengali (524288), C1ControlsAndLatin1Supplement (2), CombiningDiacriticalMarks (64), Cyrillic (256), CyrillicSupplement (512), Default (127), Devanagari (262144), GreekAndCoptic (128), Gujarati (2097152), Gurmukhi (1048576), Hebrew (2048), IpaExtensions (16), Kannada (33554432), Lao (536870912), LatinExtendedA (4), LatinExtendedB (8), Malayalam (67108864), Nko (65536), None (0), Oriya (4194304), Samaritan (131072), Sinhala (134217728), SpacingModifierLetters (32), Syriac (8192), Tamil (8388608), Telugu (16777216), Thaana (32768), Thai (268435456), Tibetan (1073741824) """
    Arabic: LowerCodeCharts = ...
    ArabicSupplement: LowerCodeCharts = ...
    Armenian: LowerCodeCharts = ...
    BasicLatin: LowerCodeCharts = ...
    Bengali: LowerCodeCharts = ...
    C1ControlsAndLatin1Supplement: LowerCodeCharts = ...
    CombiningDiacriticalMarks: LowerCodeCharts = ...
    Cyrillic: LowerCodeCharts = ...
    CyrillicSupplement: LowerCodeCharts = ...
    Default: LowerCodeCharts = ...
    Devanagari: LowerCodeCharts = ...
    GreekAndCoptic: LowerCodeCharts = ...
    Gujarati: LowerCodeCharts = ...
    Gurmukhi: LowerCodeCharts = ...
    Hebrew: LowerCodeCharts = ...
    IpaExtensions: LowerCodeCharts = ...
    Kannada: LowerCodeCharts = ...
    Lao: LowerCodeCharts = ...
    LatinExtendedA: LowerCodeCharts = ...
    LatinExtendedB: LowerCodeCharts = ...
    Malayalam: LowerCodeCharts = ...
    Nko: LowerCodeCharts = ...
    Oriya: LowerCodeCharts = ...
    Samaritan: LowerCodeCharts = ...
    Sinhala: LowerCodeCharts = ...
    SpacingModifierLetters: LowerCodeCharts = ...
    Syriac: LowerCodeCharts = ...
    Tamil: LowerCodeCharts = ...
    Telugu: LowerCodeCharts = ...
    Thaana: LowerCodeCharts = ...
    Thai: LowerCodeCharts = ...
    Tibetan: LowerCodeCharts = ...
    value__ = ...


class LowerMidCodeCharts(Enum): # skipped bases: <type 'IFormattable'>, <type 'IConvertible'>, <type 'IComparable'>, <type 'object'>
    """ enum (flags) LowerMidCodeCharts, values: Balinese (4194304), Buginese (1048576), Buhid (2048), Cherokee (32), CombiningDiacriticalMarksSupplement (536870912), Ethiopic (8), EthiopicSupplement (16), Georgian (2), HangulJamo (4), Hanunoo (1024), Khmer (8192), KhmerSymbols (524288), LatinExtendedAdditional (1073741824), Lepcha (16777216), Limbu (65536), Mongolian (16384), Myanmar (1), NewTaiLue (262144), None (0), Ogham (128), OlChiki (33554432), PhoneticExtensions (134217728), PhoneticExtensionsSupplement (268435456), Runic (256), Sudanese (8388608), Tagalog (512), Tagbanwa (4096), TaiLe (131072), TaiTham (2097152), UnifiedCanadianAboriginalSyllabics (64), UnifiedCanadianAboriginalSyllabicsExtended (32768), VedicExtensions (67108864) """
    Balinese: LowerMidCodeCharts = ...
    Buginese: LowerMidCodeCharts = ...
    Buhid: LowerMidCodeCharts = ...
    Cherokee: LowerMidCodeCharts = ...
    CombiningDiacriticalMarksSupplement: LowerMidCodeCharts = ...
    Ethiopic: LowerMidCodeCharts = ...
    EthiopicSupplement: LowerMidCodeCharts = ...
    Georgian: LowerMidCodeCharts = ...
    HangulJamo: LowerMidCodeCharts = ...
    Hanunoo: LowerMidCodeCharts = ...
    Khmer: LowerMidCodeCharts = ...
    KhmerSymbols: LowerMidCodeCharts = ...
    LatinExtendedAdditional: LowerMidCodeCharts = ...
    Lepcha: LowerMidCodeCharts = ...
    Limbu: LowerMidCodeCharts = ...
    Mongolian: LowerMidCodeCharts = ...
    Myanmar: LowerMidCodeCharts = ...
    NewTaiLue: LowerMidCodeCharts = ...
    Ogham: LowerMidCodeCharts = ...
    OlChiki: LowerMidCodeCharts = ...
    PhoneticExtensions: LowerMidCodeCharts = ...
    PhoneticExtensionsSupplement: LowerMidCodeCharts = ...
    Runic: LowerMidCodeCharts = ...
    Sudanese: LowerMidCodeCharts = ...
    Tagalog: LowerMidCodeCharts = ...
    Tagbanwa: LowerMidCodeCharts = ...
    TaiLe: LowerMidCodeCharts = ...
    TaiTham: LowerMidCodeCharts = ...
    UnifiedCanadianAboriginalSyllabics: LowerMidCodeCharts = ...
    UnifiedCanadianAboriginalSyllabicsExtended: LowerMidCodeCharts = ...
    value__ = ...
    VedicExtensions: LowerMidCodeCharts = ...


class MidCodeCharts(Enum): # skipped bases: <type 'IFormattable'>, <type 'IConvertible'>, <type 'IComparable'>, <type 'object'>
    """ enum (flags) MidCodeCharts, values: Arrows (128), BlockElements (16384), BoxDrawing (8192), BraillePatterns (1048576), CombiningDiacriticalMarksForSymbols (16), ControlPictures (1024), Coptic (134217728), CurrencySymbols (8), Dingbats (131072), EnclosedAlphanumerics (4096), EthiopicExtended (16384), GeneralPunctuation (2), GeometricShapes (32768), GeorgianSupplement (268435456), Glagolitic (33554432), GreekExtended (1), LatinExtendedC (67108864), LetterlikeSymbols (32), MathematicalOperators (256), MiscellaneousMathematicalSymbolsA (262144), MiscellaneousMathematicalSymbolsB (4194304), MiscellaneousSymbols (65536), MiscellaneousSymbolsAndArrows (16777216), MiscellaneousTechnical (512), None (0), NumberForms (64), OpticalCharacterRecognition (2048), SuperscriptsAndSubscripts (4), SupplementalArrowsA (524288), SupplementalArrowsB (2097152), SupplementalMathematicalOperators (8388608), Tifinagh (536870912) """
    Arrows: MidCodeCharts = ...
    BlockElements: MidCodeCharts = ...
    BoxDrawing: MidCodeCharts = ...
    BraillePatterns: MidCodeCharts = ...
    CombiningDiacriticalMarksForSymbols: MidCodeCharts = ...
    ControlPictures: MidCodeCharts = ...
    Coptic: MidCodeCharts = ...
    CurrencySymbols: MidCodeCharts = ...
    Dingbats: MidCodeCharts = ...
    EnclosedAlphanumerics: MidCodeCharts = ...
    EthiopicExtended: MidCodeCharts = ...
    GeneralPunctuation: MidCodeCharts = ...
    GeometricShapes: MidCodeCharts = ...
    GeorgianSupplement: MidCodeCharts = ...
    Glagolitic: MidCodeCharts = ...
    GreekExtended: MidCodeCharts = ...
    LatinExtendedC: MidCodeCharts = ...
    LetterlikeSymbols: MidCodeCharts = ...
    MathematicalOperators: MidCodeCharts = ...
    MiscellaneousMathematicalSymbolsA: MidCodeCharts = ...
    MiscellaneousMathematicalSymbolsB: MidCodeCharts = ...
    MiscellaneousSymbols: MidCodeCharts = ...
    MiscellaneousSymbolsAndArrows: MidCodeCharts = ...
    MiscellaneousTechnical: MidCodeCharts = ...
    NumberForms: MidCodeCharts = ...
    OpticalCharacterRecognition: MidCodeCharts = ...
    SuperscriptsAndSubscripts: MidCodeCharts = ...
    SupplementalArrowsA: MidCodeCharts = ...
    SupplementalArrowsB: MidCodeCharts = ...
    SupplementalMathematicalOperators: MidCodeCharts = ...
    Tifinagh: MidCodeCharts = ...
    value__ = ...


class UpperCodeCharts(Enum): # skipped bases: <type 'IFormattable'>, <type 'IConvertible'>, <type 'IComparable'>, <type 'object'>
    """ enum (flags) UpperCodeCharts, values: AlphabeticPresentationForms (4096), ArabicPresentationFormsA (8192), ArabicPresentationFormsB (524288), Cham (32), CjkCompatibilityForms (131072), CjkCompatibilityIdeographs (2048), CombiningHalfMarks (65536), DevanagariExtended (1), HalfWidthAndFullWidthForms (1048576), HangulJamoExtendedA (8), HangulJamoExtendedB (1024), HangulSyllables (512), Javanese (16), KayahLi (2), MeeteiMayek (256), MyanmarExtendedA (64), None (0), Rejang (4), SmallFormVariants (262144), Specials (2097152), TaiViet (128), VariationSelectors (16384), VerticalForms (32768) """
    AlphabeticPresentationForms: UpperCodeCharts = ...
    ArabicPresentationFormsA: UpperCodeCharts = ...
    ArabicPresentationFormsB: UpperCodeCharts = ...
    Cham: UpperCodeCharts = ...
    CjkCompatibilityForms: UpperCodeCharts = ...
    CjkCompatibilityIdeographs: UpperCodeCharts = ...
    CombiningHalfMarks: UpperCodeCharts = ...
    DevanagariExtended: UpperCodeCharts = ...
    HalfWidthAndFullWidthForms: UpperCodeCharts = ...
    HangulJamoExtendedA: UpperCodeCharts = ...
    HangulJamoExtendedB: UpperCodeCharts = ...
    HangulSyllables: UpperCodeCharts = ...
    Javanese: UpperCodeCharts = ...
    KayahLi: UpperCodeCharts = ...
    MeeteiMayek: UpperCodeCharts = ...
    MyanmarExtendedA: UpperCodeCharts = ...
    Rejang: UpperCodeCharts = ...
    SmallFormVariants: UpperCodeCharts = ...
    Specials: UpperCodeCharts = ...
    TaiViet: UpperCodeCharts = ...
    value__ = ...
    VariationSelectors: UpperCodeCharts = ...
    VerticalForms: UpperCodeCharts = ...


class UpperMidCodeCharts(Enum): # skipped bases: <type 'IFormattable'>, <type 'IConvertible'>, <type 'IComparable'>, <type 'object'>
    """ enum (flags) UpperMidCodeCharts, values: Bamum (16777216), Bopomofo (256), BopomofoExtended (2048), CjkCompatibility (32768), CjkRadicalsSupplement (4), CjkStrokes (4096), CjkSymbolsAndPunctuation (32), CjkUnifiedIdeographs (262144), CjkUnifiedIdeographsExtensionA (65536), CommonIndicNumberForms (268435456), CyrillicExtendedA (1), CyrillicExtendedB (8388608), EnclosedCjkLettersAndMonths (16384), HangulCompatibilityJamo (512), Hiragana (64), IdeographicDescriptionCharacters (16), Kanbun (1024), KangxiRadicals (8), Katakana (128), KatakanaPhoneticExtensions (8192), LatinExtendedD (67108864), Lisu (2097152), ModifierToneLetters (33554432), None (0), Phagspa (536870912), Saurashtra (1073741824), SupplementalPunctuation (2), SylotiNagri (134217728), Vai (4194304), YijingHexagramSymbols (131072), YiRadicals (1048576), YiSyllables (524288) """
    Bamum: UpperMidCodeCharts = ...
    Bopomofo: UpperMidCodeCharts = ...
    BopomofoExtended: UpperMidCodeCharts = ...
    CjkCompatibility: UpperMidCodeCharts = ...
    CjkRadicalsSupplement: UpperMidCodeCharts = ...
    CjkStrokes: UpperMidCodeCharts = ...
    CjkSymbolsAndPunctuation: UpperMidCodeCharts = ...
    CjkUnifiedIdeographs: UpperMidCodeCharts = ...
    CjkUnifiedIdeographsExtensionA: UpperMidCodeCharts = ...
    CommonIndicNumberForms: UpperMidCodeCharts = ...
    CyrillicExtendedA: UpperMidCodeCharts = ...
    CyrillicExtendedB: UpperMidCodeCharts = ...
    EnclosedCjkLettersAndMonths: UpperMidCodeCharts = ...
    HangulCompatibilityJamo: UpperMidCodeCharts = ...
    Hiragana: UpperMidCodeCharts = ...
    IdeographicDescriptionCharacters: UpperMidCodeCharts = ...
    Kanbun: UpperMidCodeCharts = ...
    KangxiRadicals: UpperMidCodeCharts = ...
    Katakana: UpperMidCodeCharts = ...
    KatakanaPhoneticExtensions: UpperMidCodeCharts = ...
    LatinExtendedD: UpperMidCodeCharts = ...
    Lisu: UpperMidCodeCharts = ...
    ModifierToneLetters: UpperMidCodeCharts = ...
    Phagspa: UpperMidCodeCharts = ...
    Saurashtra: UpperMidCodeCharts = ...
    SupplementalPunctuation: UpperMidCodeCharts = ...
    SylotiNagri: UpperMidCodeCharts = ...
    Vai: UpperMidCodeCharts = ...
    value__ = ...
    YijingHexagramSymbols: UpperMidCodeCharts = ...
    YiRadicals: UpperMidCodeCharts = ...
    YiSyllables: UpperMidCodeCharts = ...


